// API-Football 英文球员名 → 中文译名对照。
// 知名球员用通用译名，冷门球员（佛得角/沙特/突尼斯/埃及替补等）为音译，best-effort。
// 同时收录事件里出现的缩写形式（如 "A. Isak"），映射到同一中文。
// 查不到的名字在渲染层回退为英文，不会报错。
export const NAME_ZH: Record<string, string> = {
  // —— 瑞典 ——
  "Kristoffer Nordfeldt": "努德费尔特",
  "Gustaf Lagerbielke": "拉格尔别尔克",
  "Isak Hien": "希恩",
  "Victor Lindelöf": "林德洛夫",
  "Gabriel Gudmundsson": "古德蒙松",
  "G. Gudmundsson": "古德蒙松",
  "Jesper Karlström": "卡尔斯特伦",
  "J. Karlstrom": "卡尔斯特伦",
  "Yasin Ayari": "阿亚里",
  "Y. Ayari": "阿亚里",
  "Alexander Bernhardsson": "贝恩哈德松",
  "A. Bernhardsson": "贝恩哈德松",
  "Benjamin Nygren": "尼格伦",
  "B. Nygren": "尼格伦",
  "Viktor Gyökeres": "约克雷斯",
  "V. Gyokeres": "约克雷斯",
  "Alexander Isak": "伊萨克",
  "A. Isak": "伊萨克",
  "Anthony Elanga": "埃兰加",
  "A. Elanga": "埃兰加",
  "Lucas Bergvall": "贝里瓦尔",
  "L. Bergvall": "贝里瓦尔",
  "Mattias Svanberg": "斯万贝里",
  "M. Svanberg": "斯万贝里",
  "Daniel Svensson": "斯文森",
  "D. Svensson": "斯文森",
  "Elliot Stroud": "斯特劳德",
  "E. Stroud": "斯特劳德",

  // —— 突尼斯 ——
  "Abdelmouhib Chamakh": "沙马赫",
  "Yan Valery": "瓦莱里",
  "Y. Valery": "瓦莱里",
  "Omar Rekik": "雷基克",
  "O. Rekik": "雷基克",
  "Montassar Talbi": "塔尔比",
  "Amine Ben Hmida": "本·哈米达",
  "Ali Abdi": "阿卜迪",
  "Rani Khedira": "拉尼·赫迪拉",
  "R. Khedira": "赫迪拉",
  "Ellyes Skhiri": "斯希里",
  "E. Skhiri": "斯希里",
  "Hannibal Mejbri": "汉尼拔·迈杰布里",
  "H. Mejbri": "迈杰布里",
  "Elias Saad": "萨德",
  "E. Saad": "萨德",
  "Anis Ben Slimane": "本·斯利曼",
  "A. Slimane": "本·斯利曼",
  "Sebastian Tounekti": "图内克提",
  "S. Tounekti": "图内克提",
  "Elias Achouri": "阿舒里",
  "E. Achouri": "阿舒里",
  "Firas Chaouat": "沙瓦特",
  "F. Chaouat": "沙瓦特",
  "Mohamed Belhadj Mahmoud": "贝勒哈吉",
  "M. Belhadj": "贝勒哈吉",
  "Ismael Gharbi": "加尔比",
  "I. Gharbi": "加尔比",

  // —— 西班牙 ——
  "Unai Simón": "乌奈·西蒙",
  "Pedro Porro": "佩德罗·波罗",
  "Pau Cubarsí": "库巴尔西",
  "Aymeric Laporte": "拉波尔特",
  "Marc Cucurella": "库库雷利亚",
  "Marc Pubill": "普比尔",
  "Rodri": "罗德里",
  "Martín Zubimendi": "苏比门迪",
  "Mikel Merino": "梅里诺",
  "Pedri": "佩德里",
  "Pablo Gavi": "加维",
  "Fabián Ruiz": "法比安·鲁伊斯",
  "Dani Olmo": "奥尔莫",
  "Lamine Yamal": "亚马尔",
  "Nico Williams": "尼科·威廉姆斯",
  "Ferran Torres": "费兰·托雷斯",
  "Mikel Oyarzabal": "奥亚萨瓦尔",
  "Marcos Llorente": "略伦特",
  "Alex Baena": "巴埃纳",
  "Borja Iglesias": "伊格莱西亚斯",
  "Joan García": "琼·加西亚",
  "Eric García": "埃里克·加西亚",
  "David Raya": "拉亚",
  "Yéremy Pino": "皮诺",

  // —— 佛得角 ——
  "Vozinha": "沃津哈",
  "Steven Moreira": "莫雷拉",
  "Diney Borges": "博尔赫斯",
  "Sidny Lopes Cabral": "洛佩斯·卡布拉尔",
  "Logan Costa": "洛根·科斯塔",
  "Jamiro Monteiro": "蒙泰罗",
  "Kevin Lenini": "莱尼尼",
  "Deroy Duarte": "德罗伊·杜阿尔特",
  "Laros Duarte": "拉罗斯·杜阿尔特",
  "Dailon Rocha Livramento": "利夫拉门托",
  "Jovane Cabral": "若瓦内·卡布拉尔",
  "Ryan Mendes": "门德斯",
  "Garry Rodrigues": "加里·罗德里格斯",
  "Willy Semedo": "塞梅多",
  "Nuno Da Costa": "达科斯塔",
  "Telmo Arcanjo": "阿尔坎茹",
  "João Paulo": "若昂·保罗",
  "Pico": "皮科",
  "Gilson Tavares": "塔瓦雷斯",
  "Stopira": "斯托皮拉",
  "Hélio Varela": "埃利奥·瓦雷拉",
  "Kelvin Pires": "皮雷斯",

  // —— 比利时 ——
  "Thibaut Courtois": "库尔图瓦",
  "Timothy Castagne": "卡斯塔涅",
  "Brandon Mechele": "梅赫莱",
  "Nathan Ngoy": "恩戈伊",
  "Maxim De Cuyper": "德库伊佩尔",
  "Thomas Meunier": "默尼耶",
  "Amadou Onana": "奥纳纳",
  "Youri Tielemans": "蒂勒曼斯",
  "Hans Vanaken": "瓦纳肯",
  "Nicolas Raskin": "拉斯金",
  "Charles De Ketelaere": "德凯特拉雷",
  "Kevin De Bruyne": "德布劳内",
  "Jérémy Doku": "多库",
  "Leandro Trossard": "特罗萨德",
  "Romelu Lukaku": "卢卡库",
  "Dodi Lukebakio": "卢凯巴基奥",
  "Alexis Saelemaekers": "萨勒马克斯",
  "Matías Fernández-Pardo": "费尔南德斯-帕尔多",
  "Arthur Theate": "特亚特",
  "Koni De Winter": "德温特",
  "Axel Witsel": "维特塞尔",
  "Hans Vanaken ": "瓦纳肯",

  // —— 埃及 ——
  "Mostafa Shobeir": "舒贝尔",
  "Mohamed Hany": "哈尼",
  "Rami Rabia": "拉比亚",
  "Yasser Ibrahim": "亚西尔·易卜拉欣",
  "Ahmed Fatouh": "法图赫",
  "Karim Hafez": "哈菲兹",
  "Hamdy Fathy": "法蒂",
  "Marwan Attia": "阿提亚",
  "Emam Ashour": "阿舒尔",
  "Mohamed Salah": "萨拉赫",
  "Omar Marmoush": "马尔穆什",
  "Zizo": "齐祖",
  "Ibrahim Adel": "易卜拉欣·阿德尔",
  "Mostafa Ziko": "齐科",
  "Mohanad Lasheen": "拉欣",
  "Hamza Abdelkarim": "阿卜杜勒卡里姆",
  "Mahmoud Saber": "萨贝尔",
  "Mohamed Abdelmonem": "阿卜杜勒蒙内姆",
  "Mohamed El-Shenawy": "谢纳维",
  "Mahmoud Trézéguet": "特雷泽盖",

  // —— 沙特阿拉伯 ——
  "Mohammed Al-Owais": "奥瓦伊斯",
  "Saud Abdulhamid": "阿卜杜勒哈米德",
  "Abdulelah Al-Amri": "阿姆里",
  "Hassan Altambakti": "坦巴克提",
  "Moteb Al-Harbi": "哈尔比",
  "Mohammed Abu Al-Shamat": "阿布·沙马特",
  "Mohamed Kanno": "卡诺",
  "Abdullah Al-Khaibari": "海巴里",
  "Salem Al-Dawsari": "萨利姆·达瓦萨里",
  "Firas Al-Buraikan": "布赖坎",
  "Musab Al Juwayr": "朱韦尔",
  "Nasser Al-Dawsari": "纳赛尔·达瓦萨里",
  "Ala'a Al-Hejji": "赫吉",
  "Abdullah Al-Hamdan": "哈姆丹",
  "Ali Lajami": "拉杰米",
  "Nawaf Boushal": "布沙尔",
  "Saleh Al-Shehri": "谢赫里",
  "Khalid Al-Ghannam": "甘纳姆",
  "Ayman Yahya": "叶海亚",
  "Ziyad Aljohani": "乔哈尼",
  "Nawaf Al-Aqidi": "阿基迪",
  "Ali Majrashi": "马杰拉希",
  "Hassan Kadesh": "卡迪什",

  // —— 乌拉圭 ——
  "Fernando Muslera": "穆斯莱拉",
  "Guillermo Varela": "巴雷拉",
  "Sebastián Cáceres": "卡塞雷斯",
  "Mathías Olivera": "奥利维拉",
  "Matías Viña": "维尼亚",
  "Manuel Ugarte": "乌加特",
  "Rodrigo Bentancur": "本坦库尔",
  "Federico Valverde": "巴尔韦德",
  "Federico Viñas": "维尼亚斯",
  "Maximiliano Araújo": "阿劳霍",
  "Darwin Núñez": "努涅斯",
  "Agustín Canobbio": "卡诺比奥",
  "Juan Sanabria": "萨纳夫里亚",
  "Nicolás de la Cruz": "德拉克鲁斯",
  "Brian Rodríguez": "布莱恩·罗德里格斯",
  "Rodrigo Aguirre": "阿吉雷",
  "Santiago Bueno": "布埃诺",
  "José María Giménez": "希门尼斯",
  "Rodrigo Zalazar": "萨拉萨尔",
  "Facundo Pellistri": "佩利斯特里",
  "Emiliano Martínez": "马丁内斯",

  // —— 德国 ——
  "Manuel Neuer": "诺伊尔",
  "Oliver Baumann": "鲍曼",
  "Alexander Nübel": "纽贝尔",
  "Antonio Rüdiger": "吕迪格尔",
  "Jonathan Tah": "塔",
  "David Raum": "劳姆",
  "Nico Schlotterbeck": "施洛滕贝克",
  "Waldemar Anton": "安东",
  "Joshua Kimmich": "基米希",
  "Leon Goretzka": "戈雷茨卡",
  "Kai Havertz": "哈弗茨",
  "Florian Wirtz": "维尔茨",
  "Jamal Musiala": "穆西亚拉",
  "Leroy Sané": "萨内",
  "Maximilian Beier": "拜尔",
  "Nick Woltemade": "沃尔特马德",
  "Felix Nmecha": "恩梅查",
  "Pascal Groß": "格罗斯",
  "Angelo Stiller": "斯蒂勒",
  "Jamie Leweling": "勒维林",
  "Aleksandar Pavlović": "帕夫洛维奇",
  "Deniz Undav": "温达夫",
  "Assan Ouédraogo": "奥德拉奥戈",
  "Malick Thiaw": "蒂亚",
  "Nadiem Amiri": "阿米里",

  // —— 库拉索 ——
  "Eloy Room": "鲁姆",
  "Shurandy Sambo": "桑博",
  "Armando González": "阿尔曼多·冈萨雷斯",
  "Roshon van Eijma": "范艾马",
  "Brandley Kuwas": "库瓦斯",
  "Kevin Felida": "费利达",
  "Jurien Gaari": "加里",
  "Garven-Michee Metusala": "梅图萨拉",
  "Jearl Margaritha": "马尔加里塔",
  "Gervane Kastaneer": "卡斯塔内尔",
  "Godfried Roemeratoe": "鲁梅拉托",
  "Kenji Gorré": "戈雷",
  "Nando Pijnaker": "派纳克尔",
  "Sontje Hansen": "汉森",
  "Trevor Iriving Doornbusch": "多恩布施",
  "Juninho Bacuna": "胡尼尼奥·巴库纳",
  "Jürgen Locadia": "洛卡迪亚",
  "Tyrese Noslin": "诺斯林",
  "Riechedly Bazoer": "巴佐尔",
  "Leandro Bacuna": "莱安德罗·巴库纳",
  "Tyrick Bodak": "博达克",
  "Sherel Constancio Floranus": "弗洛拉努斯",
  "Livano Comenencia": "科梅嫩西亚",
  "Ar'Jany Martha": "马尔塔",
  "CJ Dos Santos": "多斯·桑托斯",

  // —— 荷兰 ——
  "Bart Verbruggen": "费尔布吕根",
  "Mark Flekken": "弗莱肯",
  "Robin Roefs": "鲁弗斯",
  "Virgil van Dijk": "范迪克",
  "Nathan Aké": "阿克",
  "Micky van de Ven": "范德芬",
  "Denzel Dumfries": "邓弗里斯",
  "Jan Paul van Hecke": "范赫克",
  "Jorrel Hato": "哈托",
  "Lutsharel Geertruida": "赫尔特鲁伊达",
  "Quinten Timber": "昆滕·廷伯",
  "Frenkie de Jong": "弗雷基·德容",
  "Ryan Gravenberch": "格拉芬贝赫",
  "Tijjani Reijnders": "雷因德斯",
  "Teun Koopmeiners": "库普梅纳斯",
  "Marten de Roon": "德龙",
  "Guus Til": "蒂尔",
  "Donyell Malen": "马伦",
  "Cody Gakpo": "加科波",
  "Wout Weghorst": "韦格霍斯特",
  "Memphis Depay": "孟菲斯·德佩",
  "Brian Brobbey": "布罗比",
  "Justin Kluivert": "贾斯廷·克鲁伊维特",
  "Noa Lang": "朗",
  "Tahith Chong": "钟塔希斯",
  "Anass Salah-Eddine": "萨拉赫-埃丁",

  // —— 日本 ——
  "Zion Suzuki": "铃木朱旺",
  "Ko Itakura": "板仓滚",
  "Shogo Taniguchi": "谷口彰悟",
  "Hiroki Itō": "伊藤洋辉",
  "Takehiro Tomiyasu": "富安健洋",
  "Daichi Kamada": "镰田大地",
  "Ao Tanaka": "田中碧",
  "Ayumu Seko": "濑古步梦",
  "Kaishu Sano": "佐野海舟",
  "Yukinari Sugawara": "菅原由势",
  "Daizen Maeda": "前田大然",
  "Ritsu Doan": "堂安律",
  "Junya Ito": "伊东纯也",
  "Takefusa Kubo": "久保建英",
  "Keito Nakamura": "中村敬斗",
  "Koki Ogawa": "小川航基",
  "Ayase Ueda": "上田绮世",
  "Yuito Suzuki": "铃木唯人",
  "Shuto Machino": "町野修斗",
  "Yuto Nagatomo": "长友佑都",
  "Keisuke Osako": "大迫勇也",
  "Junnosuke Suzuki": "铃木准之助",
  "Tomoki Hayakawa": "早川友基",
  "Tsuyoshi Watanabe": "渡边刚",
  "Kento Shiogai": "盐谷司",
  "Keisuke Goto": "后藤启介",

  // —— 科特迪瓦 ——
  "Yahia Fofana": "福法纳",
  "Senne Lammens": "拉门斯",
  "Odilon Kossounou": "科苏努",
  "Wilfried Singo": "辛戈",
  "Ghislain Konan": "科南",
  "Ousmane Diomande": "迪奥曼德",
  "Evan Ndicka": "恩迪卡",
  "Issa Diop": "伊萨·迪奥普",
  "Emmanuel Agbadou": "阿格巴杜",
  "Jean Michaël Seri": "塞里",
  "Franck Kessié": "凯西",
  "Ibrahim Sangaré": "桑加雷",
  "Seko Fofana": "塞科·福法纳",
  "Mohamed Koné": "科内",
  "Simon Adingra": "阿丁格拉",
  "Nicolás Pépé": "佩佩",
  "Nicolas Pépé": "佩佩",
  "Oumar Diakité": "迪亚基特",
  "Guéla Doué": "杜韦",
  "Yan Diomande": "颜·迪奥曼德",
  "Parfait Guiagon": "圭亚贡",
  "Evann Guessand": "盖桑",

  // —— 摩洛哥 ——
  "Ahmed Reda Tagnaouti": "塔尼奥蒂",
  "Bono": "博诺",
  "Munir El Kajoui": "卡茹伊",
  "Achraf Hakimi": "哈基米",
  "Noussair Mazraoui": "马兹劳伊",
  "Sofyan Amrabat": "安拉巴特",
  "Azzedine Ounahi": "乌纳希",
  "Ayoub El Kaabi": "卡阿比",
  "Bilal El Khannouss": "卡努斯",
  "Ayoub Al Oui": "阿卢维",
  "Zakaria El Ouahdi": "埃尔·瓦迪",
  "Soufiane Rahimi": "拉希米",
  "Amine Sbai": "斯巴伊",
  "Abdelaziz Hatem": "哈泰姆",
  "Neil El Aynaoui": "艾纳乌伊",
  "Ayyoub Bouaddi": "布阿迪",
  "Samir El Mourabet": "穆拉贝特",
  "Ayoube Amaimouni Echghouyab": "阿迈穆尼",
  "Nabil Donga": "唐加",
  "Redouane Halhal": "哈尔哈尔",
  "Chemsdine Talbi": "塔尔比",

  // —— 巴西 ——
  "Alisson": "阿利松",
  "Éderson": "埃德尔森",
  "Weverton": "韦弗顿",
  "Danilo": "达尼洛",
  "Alex Sandro": "亚历克斯·桑德罗",
  "Marquinhos": "马尔基尼奥斯",
  "Bremer": "布雷默",
  "Gabriel Magalhães": "加布里埃尔·马加良斯",
  "Casemiro": "卡塞米罗",
  "Fabinho": "法比尼奥",
  "Bruno Guimarães": "布鲁诺·吉马良斯",
  "Lucas Paquetá": "帕凯塔",
  "Raphinha": "拉菲尼亚",
  "Vinícius Júnior": "维尼修斯",
  "Matheus Cunha": "库尼亚",
  "Endrick": "恩德里克",
  "Gabriel Martinelli": "马丁内利",
  "Léo Pereira": "莱奥·佩雷拉",
  "Igor Thiago": "伊戈尔·蒂亚戈",
  "Luiz Henrique": "路易斯·恩里克",
  "Roger Ibañez": "伊巴涅斯",
  "Douglas Santos": "道格拉斯·桑托斯",
  "Danilo Santos": "达尼洛·桑托斯",
  "Edmilson Junior": "埃德米尔森·朱尼奥尔",
  "Mauricio": "毛里西奥",
  "Rayan": "拉扬",
  "Márcio Rosa": "马西奥·罗萨",

  // —— 南非 ——
  "Ronwen Williams": "罗恩文·威廉姆斯",
  "Sipho Chaine": "乔内",
  "Thapelo Maseko": "马塞科",
  "Aubrey Modiba": "莫迪巴",
  "Teboho Mokoena": "莫科纳",
  "Evidence Makgopa": "马克戈帕",
  "Oswin Appollis": "阿波利斯",
  "Khuliso Mudau": "穆道",
  "Nkosinathi Sibisi": "西比西",
  "Mbekezeli Mbokazi": "姆博卡齐",
  "Relebohile Mofokeng": "莫福肯",
  "Thalente Mbatha": "姆巴塔",
  "Sphephelo Sithole": "西托莱",
  "Lyle Foster": "莱尔·福斯特",
  "Iqraam Rayners": "雷纳斯",
  "Nishan Velupillay": "韦卢皮莱",
  "Olwethu Makhanya": "马卡尼亚",
  "Kamogelo Sebelebele": "塞贝莱贝莱",
  "Samukelo Kabini": "卡比尼",
  "Yassin Fortune": "福尔顿",
  "Khulumani Ndamane": "恩达马内",
  "Themba Zwane": "兹万内",
  "Promise David": "普罗米斯·大卫",
  "Tshepang Moremi": "莫雷米",
  "Tholo Thabang Matuludi": "马图卢迪",
  "Nkosi Sibisi": "西比西",

  // —— 澳大利亚 ——
  "Mathew Ryan": "马修·莱恩",
  "Paul Izzo": "保罗·伊佐",
  "Harry Souttar": "哈里·苏塔尔",
  "Miloš Degenek": "德格内克",
  "Aziz Behich": "贝希奇",
  "Aiden O'Neill": "奥尼尔",
  "Nestory Irankunda": "伊朗昆达",
  "Mathew Leckie": "莱克利",
  "Jackson Irvine": "杰克逊·欧文",
  "Awer Mabil": "马比尔",
  "Jordan Bos": "乔丹·博斯",
  "Tete Yengi": "特特·延基",
  "Christopher Operi": "克里斯托弗·奥佩里",
  "Callan Elliot": "卡兰·埃利奥特",
  "Jacob Italiano": "雅各布·意大利亚诺",
  "Alex Gersbach": "格斯巴赫",
  "Lachlan Bayliss": "拉克伦·贝利斯",

  // —— 土耳其 ——
  "Uğurcan Çakır": "恰克尔",
  "Altay Bayındır": "拜因迪尔",
  "Mert Günok": "古诺克",
  "Çağlar Söyüncü": "索云朱",
  "Merih Demiral": "德米拉尔",
  "Samet Akaydın": "阿凯丁",
  "Zeki Çelik": "切利克",
  "Ozan Kabak": "卡巴克",
  "Kaan Ayhan": "艾汉",
  "Abdülkerim Bardakcı": "巴尔达克奇",
  "Hakan Çalhanoğlu": "查尔汉诺卢",
  "Arda Güler": "居勒尔",
  "Kerem Aktürkoğlu": "阿克图尔科卢",
  "Ferdi Kadıoğlu": "卡迪奥卢",
  "Orkun Kökçü": "科克丘",
  "İrfan Can Kahveci": "伊尔凡·坎",
  "İsmail Yüksek": "于克塞克",
  "Kenan Yıldız": "耶尔迪兹",
  "Can Uzun": "乌尊",
  "Salih Özcan": "奥兹坎",
  "Barış Alper Yılmaz": "耶尔马兹",
  "Yunus Akgün": "阿克贡",
  "Oğuz Aydın": "艾丁",
  "Eren Elmalı": "埃尔马利",
  "Deniz Gül": "德尼兹·居尔",
  "Eray Cömert": "科梅尔特",
  "Mert Müldür": "米尔杜尔",

  // —— 韩国 ——
  "Kim Seung-gyu": "金承圭",
  "Jo Hyeonwoo": "赵贤宇",
  "Kim Min-jae": "金玟哉",
  "Kim Moon-hwan": "金文焕",
  "Lee Tae-seok": "李泰锡",
  "Son Heung-min": "孙兴慜",
  "Jae-sung Lee": "李在成",
  "Hwang Hee-chan": "黄喜灿",
  "Hwang In-beom": "黄仁范",
  "Kang-in Lee": "李康仁",
  "Gue-sung Cho": "曹圭成",
  "Hyeon-gyu Oh": "吴铉奎",
  "Seung Ho Paik": "白承昊",
  "Dong-gyeong Lee": "李东经",
  "Yang Hyun-Jun": "杨贤俊",
  "Jun-Ho Bae": "裴俊昊",
  "Han-Beom Lee": "李汉范",
  "Ji-sung Eom": "严智成",
  "Song Bum-keun": "宋凡根",
  "Wi-je Cho": "曹围济",
  "Jin-gyu Kim": "金进圭",
  "Jin-seob Park": "朴镇燮",
  "Gi-Hyuk Lee": "李基赫",
  "Young-woo Seol": "薛英宇",
  "Kim Tae-hyeon": "金泰贤",

  // —— 捷克 ——
  "Jindřich Staněk": "斯塔内克",
  "Matěj Kovář": "科瓦日",
  "Vladimír Coufal": "科法尔",
  "Tomáš Holeš": "霍莱什",
  "Lukáš Horníček": "霍尔尼切克",
  "Robin Hranáč": "拉纳奇",
  "David Douděra": "杜代拉",
  "David Jurásek": "于拉塞克",
  "David Zima": "吉马",
  "Ladislav Krejčí": "克雷伊奇",
  "Lukáš Provod": "普罗沃德",
  "Tomáš Souček": "苏切克",
  "Vladimír Darida": "达里达",
  "Lukáš Červ": "切尔夫",
  "Adam Hložek": "赫洛热克",
  "Patrik Schick": "希克",
  "Tomáš Chorý": "霍里",
  "Mojmír Chytil": "希蒂尔",
  "Jan Kuchta": "库赫塔",
  "Michal Sadílek": "萨迪莱克",
  "Pavel Šulc": "舒尔茨",
  "Alexandr Sojka": "索伊卡",
  "Denis Višinský": "维辛斯基",
  "Hugo Sochurek": "索赫雷克",
  "Jaroslav Zelený": "泽莱内",
  "Štěpán Chaloupek": "哈卢佩克",

  // —— 加拿大 ——
  "Dayne St. Clair": "圣克莱尔",
  "Maxime Crépeau": "克雷波",
  "Derek Cornelius": "科内利乌斯",
  "Moise Bombito": "邦比托",
  "Alistair Johnston": "约翰斯顿",
  "Richie Laryea": "拉里亚",
  "Stephen Eustaquio": "尤斯塔基奥",
  "Ismael Koné": "科内",
  "Tajon Buchanan": "布坎南",
  "Jonathan David": "乔纳森·大卫",
  "Cyle Larin": "拉林",
  "Alphonso Davies": "阿方索·戴维斯",
  "Jacob Shaffelburg": "沙菲尔伯格",
  "Mathieu Choinière": "舒瓦尼埃尔",
  "Jonathan Osorio": "奥索里奥",
  "Mark McKenzie": "麦肯齐",
  "Joel Waterman": "沃特曼",
  "Cameron Burgess": "伯吉斯",
  "Liam Millar": "利亚姆·米勒",
  "Lucas Mendes": "卢卡斯·门德斯",
  "Jayden Nelson": "杰登·纳尔逊",
  "Jayden Adams": "杰登·亚当斯",
  "Nathan-Dylan Saliba": "萨利巴",
  "Nathan Brown": "内森·布朗",

  // —— 波黑 ——
  "Nikola Vasilj": "瓦西利",
  "Armin Gigović": "吉戈维奇",
  "Sead Kolašinac": "科拉希纳茨",
  "Amar Dedić": "德迪奇",
  "Edin Džeko": "哲科",
  "Ermin Mahmic": "马赫米奇",
  "Amir Hadžiahmetović": "哈吉阿赫梅托维奇",
  "Ermedin Demirović": "德米罗维奇",
  "Ivan Šunjić": "舒尼奇",
  "Ivan Bašić": "巴希奇",
  "Benjamin Tahirović": "塔希罗维奇",
  "Tarik Muharemović": "穆哈雷莫维奇",
  "Amar Memić": "梅米奇",
  "Nihad Mujakić": "穆亚基奇",
  "Esmir Bajraktarević": "拜拉克塔雷维奇",
  "Dennis Hadžikadunić": "哈吉卡杜尼奇",
  "Haris Tabaković": "塔巴科维奇",
  "Dženis Burnić": "布尔尼奇",
  "Marko Stamenić": "斯塔梅尼奇",
  "Besfort Zeneli": "泽内利",
  "Jovo Lukić": "卢基奇",
  "Martin Zlomislić": "兹洛米斯利奇",
  "Samed Baždar": "巴日达尔",
  "Stjepan Radeljić": "拉代利奇",
  "Kerim Alajbegović": "阿拉伊贝戈维奇",
  "Arjan Malić": "马利奇",

  // —— 卡塔尔 ——
  "Meshaal Barsham": "巴尔沙姆",
  "Boualem Khoukhi": "胡基",
  "Hassan Al Haydos": "哈伊多斯",
  "Akram Afif": "阿菲夫",
  "Almoez Ali": "阿尔穆兹·阿里",
  "Assim Madibo": "马迪博",
  "Mohammed Muntari": "蒙塔里",
  "Pedro Miguel": "佩德罗·米格尔",
  "Homam Al-Amin": "霍马姆·阿明",
  "Karim Boudiaf": "布迪亚夫",
  "Sultan Mandash": "曼达什",
  "Al-Hashmi Al-Hussain": "胡赛因",
  "Jassem Gaber Abdulsallam": "贾西姆·加伯",
  "Yusuf Abdurisag": "尤素福",
  "Ahmed Al-Ganehi": "加尼希",
  "Ahmed Al-Kassar": "卡萨尔",
  "Aiman Ghanoum": "加努姆",

  // —— 瑞士 ——
  "Gregor Kobel": "科贝尔",
  "Yvon Mvogo": "姆沃戈",
  "Mike Penders": "彭德斯",
  "Manuel Akanji": "阿坎吉",
  "Ricardo Rodríguez": "里卡多·罗德里格斯",
  "Nico Elvedi": "埃尔韦迪",
  "Miro Muheim": "穆海姆",
  "Silvan Widmer": "维德默",
  "Granit Xhaka": "沙卡",
  "Denis Zakaria": "扎卡里亚",
  "Remo Freuler": "弗罗伊勒",
  "Djibril Sow": "索",
  "Michel Aebischer": "艾比舍",
  "Fabian Rieder": "里德尔",
  "Breel Embolo": "恩博洛",
  "Zeki Amdouni": "阿姆杜尼",
  "Noah Okafor": "奥卡福",
  "Dan Ndoye": "恩多耶",
  "Ardon Jashari": "贾沙里",
  "Christian Fassnacht": "法斯纳赫特",
  "Rubén Vargas": "鲁本·巴尔加斯",
  "Aurèle Amenda": "阿芒达",
  "Fabian Schär": "沙尔",
  "Cédric Itten": "塞德里克·伊滕",
  "Marvin Keller": "凯勒",

  // —— 海地 ——
  "Johny Placide": "普拉西德",
  "Duckens Nazon": "纳松",
  "Carlens Arcus": "阿尔库斯",
  "Frantzdy Pierrot": "皮埃罗",
  "Jean-Kévin Duverne": "迪韦尔纳",
  "Derrick Etienne": "德里克·艾蒂安",
  "Deveron Fonville": "丰维尔",
  "Alexandre Pierre": "亚历山大·皮埃尔",
  "Josué Casimir": "卡西米尔",
  "Josué Duverger": "迪韦尔热",
  "Louicius Don Deedson": "迪德森",
  "Wilguens Paugain": "波甘",
  "Luc De Fougerolles": "德富热罗尔",
  "Carl Fred Sainté": "圣泰",
  "Duke Lacroix": "拉克鲁瓦",
  "Danley Jean Jacques": "让-雅克",
  "Martin Expérience": "埃克斯佩里昂斯",
  "Keeto Thermoncy": "泰尔蒙西",
  "Ruben Providence": "普罗维当斯",
  "Woodensky Pierre": "吴登斯基·皮埃尔",
  "Niko Sigur": "尼科·西古尔",
  "Nikola Katić": "卡提奇",

  // —— 苏格兰 ——
  "Craig Gordon": "克雷格·戈登",
  "Angus Gunn": "安格斯·甘恩",
  "Andy Robertson": "安迪·罗伯逊",
  "Jack Hendry": "杰克·亨德里",
  "John Souttar": "约翰·苏塔尔",
  "Scott McKenna": "斯科特·麦肯纳",
  "Grant Hanley": "格兰特·汉利",
  "Kenny McLean": "肯尼·麦克莱恩",
  "John McGinn": "约翰·麦金",
  "Scott McTominay": "麦托米奈",
  "Ryan Christie": "瑞安·克里斯蒂",
  "Lewis Ferguson": "刘易斯·弗格森",
  "Lawrence Shankland": "劳伦斯·尚克兰",
  "Che Adams": "切·亚当斯",
  "Lyndon Dykes": "迪克斯",
  "Aaron Hickey": "亚伦·希基",
  "Nathan Patterson": "内森·帕特森",
  "Dominic Hyam": "多米尼克·海姆",
  "George Hirst": "乔治·赫斯特",
  "Ross Stewart": "罗斯·斯图尔特",
  "Ben Gannon-Doak": "甘农-多克",
  "Callum McCowatt": "麦考瓦特",
  "Tony Ralston": "托尼·拉尔斯顿",
  "Findlay Curtis": "芬德莱·柯蒂斯",
  "Liam Kelly": "利亚姆·凯利",

  // —— 美国 ——
  "Matt Turner": "特纳",
  "Chris Brady": "布雷迪",
  "Auston Trusty": "奥斯顿·特拉斯提",
  "Chris Richards": "克里斯·理查兹",
  "Tim Ream": "蒂姆·里姆",
  "Miles Robinson": "迈尔斯·罗宾逊",
  "Antonee Robinson": "安托尼·罗宾逐",
  "Joe Scally": "乔·斯卡利",
  "Sergiño Dest": "塞吉尼奥·德斯特",
  "Tyler Adams": "泰勒·亚当斯",
  "Weston McKennie": "韦斯顿·麦肯尼",
  "Brenden Aaronson": "布伦登·阿伦森",
  "Cristian Roldán": "克里斯蒂安·罗尔丹",
  "Giovanni Reyna": "乔凡尼·雷纳",
  "Christian Pulišić": "普利西奇",
  "Ricardo Pepi": "里卡多·佩皮",
  "Folarin Balogun": "福拉林·巴洛贡",
  "Haji Wright": "哈吉·赖特",
  "Tim Weah": "蒂姆·韦",
  "Tani Oluwaseyi": "奥卢瓦塞伊",
  "Sebastian Berhalter": "贝哈尔特",
  "Brian Gutiérrez": "布莱恩·古铁雷斯",
  "Alex Freeman": "亚历克斯·弗里曼",
  "Obed Vargas": "奥贝德·巴尔加斯",
  "Patrick Beach": "帕特里克·比奇",
  "Elijah Just": "以利亚·贾斯特",
  "Matthew Freese": "马修·弗里斯",
  "Nathaniel Brown": "纳撒尼尔·布朗",
  "Malik Tillman": "马利克·蒂尔曼",
  "Jesse Randall": "杰西·兰德尔",
  "Cristian Volpato": "克里斯蒂安·沃尔帕托",

  // —— 厄瓜多尔 ——
  "Hernán Galíndez": "加林德斯",
  "Piero Hincapié": "因卡皮耶",
  "Willian Pacho": "帕乔",
  "Félix Torres": "费利克斯·托雷斯",
  "Pervis Estupiñán": "埃斯图皮尼安",
  "Ángelo Preciado": "普雷西亚多",
  "Joel Ordóñez": "奥尔多涅斯",
  "Jackson Porozo": "波罗索",
  "Alan Franco": "阿兰·弗兰科",
  "Moisés Caicedo": "凯塞多",
  "Kendry Páez": "肯德里·帕耶斯",
  "Gonzalo Plata": "冈萨洛·普拉塔",
  "Kevin Rodriguez": "凯文·罗德里格斯",
  "Enner Valencia": "恩内尔·巴伦西亚",
  "Alan Minda": "阿兰·明达",
  "Nilson Angulo": "安古洛",
  "Jeremy Arevalo": "阿雷瓦洛",
  "Jordy Alcivar": "阿尔西瓦尔",
  "Alex Arce": "阿列克斯·阿尔塞",
  "Jordy Caicedo": "霍迪·凯塞多",
  "Anthony Valencia": "安东尼·巴伦西亚",
  "Moisés Ramírez": "莫伊塞斯·拉米雷斯",
  "Pedro Vite": "佩德罗·维特",

  // —— 伊朗 ——
  "Alireza Beiranvand": "拜兰万德",
  "Hossein Hosseini": "侯赛尼",
  "Ali Alipour": "阿利普尔",
  "Ehsan Hajsafi": "哈吉萨菲",
  "Ramin Rezaeian": "雷扎伊安",
  "Saman Ghoddos": "戈多斯",
  "Mehdi Torabi": "托拉比",
  "Mehdi Ghayedi": "加伊迪",
  "Mehdi Taremi": "塔雷米",
  "Alireza Jahanbakhsh": "贾汉巴赫什",
  "Saeid Ezatolahi": "依扎托拉希",
  "Danial Eiri": "埃里",
  "Aria Yousefi": "尤西菲",
  "Roozbeh Cheshmi": "切什米",
  "Mohammad Ghorbani": "戈尔巴尼",
  "Mohammad Mohebi": "穆赫比",
  "Payam Niazmand": "尼亚兹曼德",
  "Shoja Khalilzadeh": "哈利勒扎德",
  "Ali Nemati": "内马提",
  "Amirhossein Hosseinzadeh": "侯赛因扎德",
  "Amirmohammad Razzaghinia": "拉扎尼亚",
  "Hossein Kanaani": "卡纳尼",
  "Saleh Hardani": "哈达尼",
  "Milad Mohammadi": "穆罕默迪",
  "Shahriar Moghanlou": "莫加努",
  "Tahsin Mohammed Jamshid": "贾姆希德",

  // —— 新西兰 ——
  "Max Crocombe": "克罗康比",
  "Michael Woud": "韦德",
  "Michael Boxall": "博克索尔",
  "Liberato Cacace": "卡卡切",
  "Tyler Bindon": "宾登",
  "Ben Waine": "韦恩",
  "Alex Rufer": "鲁费尔",
  "Joe Bell": "乔·贝尔",
  "Alex Paulsen": "保尔森",
  "Chris Wood": "克里斯·伍德",
  "Finn Surman": "费恩·瑟曼",
  "Sarpreet Singh": "萨尔普里特·辛格",
  "Kosta Barbarouses": "巴尔巴鲁斯",
  "Tim Payne": "蒂姆·佩恩",
  "Kai Trewin": "凯·特鲁温",
  "Ryan Thomas": "瑞安·托马斯",
  "Tommy Smith": "汤米·史密斯",
  "Lucas Herrington": "赫林顿",
  "Jason Geria": "格利亚",
  "Cameron Devlin": "卡梅伦·德夫林",
  "Tyler Fletcher": "弗莱彻",
  "Connor Metcalfe": "麦特卡尔夫",
  "Owen Goodman": "欧文·古德曼",

  // —— 墨西哥 ——
  "Guillermo Ochoa": "吉列尔莫·奥乔亚",
  "Carlos Acevedo": "阿塞韦多",
  "Raúl Rangel": "劳尔·兰赫尔",
  "César Montes": "塞萨尔·蒙特斯",
  "Jesús Gallardo": "赫苏斯·加利亚多",
  "Johan Vásquez": "约翰·巴斯克斯",
  "Jorge Sánchez": "乔治·桑切斯",
  "Edson Álvarez": "埃德森·阿尔瓦雷斯",
  "Luis Chávez": "路易斯·查韦斯",
  "Orbelín Pineda": "皮内达",
  "Luis Romo": "路易斯·罗莫",
  "Roberto Alvarado": "罗贝托·阿尔瓦拉多",
  "Raúl Jiménez": "劳尔·希门尼斯",
  "Alexis Vega": "阿列克西斯·贝加",
  "Erik Lira": "埃里克·利拉",
  "Alex Zendejas": "泽恩德哈斯",
  "Israel Reyes": "以色列·雷耶斯",
  "Julián Quiñones": "基尼奥内斯",
  "César Huerta": "塞萨尔·韦尔塔",
  "Víctor Muñoz": "维克托尔·穆尼奥斯",
  "Álvaro Fidalgo": "阿尔瓦罗·菲达尔戈",
  "Santiago Giménez": "圣地亚哥·希门尼斯",
  "Roberto Fernández": "费尔南德斯",

  // —— 巴拉圭 ——
  "Gastón Olveira": "奥尔韦拉",
  "Santiago Mele": "圣地亚哥·梅莱",
  "Sergio Rochet": "罗切特",
  "Fabián Balbuena": "巴尔布埃纳",
  "Omar Alderete": "奥马尔·阿尔德雷特",
  "Gustavo Gómez": "古斯塔沃·戈麦斯",
  "Junior Alonso": "胡尼奥尔·阿隆索",
  "Braian Ojeda": "奥赫达",
  "Andrés Cubas": "库巴斯",
  "Damián Bobadilla": "鲍巴迪利亚",
  "Gabriel Ávalos": "加布里埃尔·阿瓦洛斯",
  "Miguel Almirón": "阿尔米隆",
  "Matías Galarza": "加拉尔萨",
  "Ramón Sosa": "拉蒙·索萨",
  "Julio Enciso": "恩西索",
  "Gustavo Caballero": "卡瓦列罗",
  "Guillermo Martínez": "吉列尔莫·马丁内斯",
  "Diego Gómez": "迭戈·戈麦斯",
  "Armando Obispo": "奥比斯波",
  "Juan Cáceres": "胡安·卡塞雷斯",
  "Antonio Sanabria": "安东尼奥·萨纳夫里亚",

  // —— 阿尔及利亚 ——
  "Rayan Elloumi": "拉扬·埃卢米",
  "Adem Arous": "阿鲁斯",
  "Ali Ahmed": "阿里·艾哈迈德",
  "Gessime Yassine": "亚辛·格西梅",
  "Raed Chikhaoui": "希克豪伊",
  "Taha Abdi Ali": "塔哈·阿卜迪·阿里",

  // —— 其他球员 ——
  "Alban Lafont": "阿尔班·拉方",
  "Alejandro Grimaldo": "阿莱杭德罗·格里马尔多",
  "Alejandro Romero": "阿莱杭德罗·罗梅罗",
  "Eric Smith": "埃里克·史密斯",
  "Jacob Widell Zetterström": "泽特斯特伦",
  "Dominique Simon": "多米尼克·西蒙",
  "Benjamin Old": "本杰明·奥尔德",
  "Issa Laye": "伊萨·莱耶",
  "Johan Manzambi": "曼赞比",

  // 瑞典补充
  "Viktor Johansson": "维克托·约翰森",
  "Hjalmar Ekdal": "希亚尔马尔·埃克达尔",
  "Carl Starfelt": "卡尔·斯塔费尔特",
  "Herman Johansson": "赫尔曼·约翰森",
  "Ken Sema": "塞马",
  "Gustaf Nilsson": "古斯塔夫·尼尔森",

  // 突尼斯补充
  "Aymen Dahmen": "达门",
  "Sabri Ben Hessen": "本·海森",
  "Dylan Bronn": "布隆",
  "Moataz Nefati": "内法提",
  "Mortadha Ben Ouanes": "本·瓦内斯",
  "Khalil Ayari": "阿亚里",
  "Hazem Mastouri": "马斯图里",
  "Youssef Belammari": "贝拉姆里",
  "Marwane Saadane": "萨达内",
  "Mohamed Naceur Almanai": "阿尔马纳伊",

  // 卡塔尔补充
  "Jehad Thakri": "塔克里",
  "Mahmud Abunada": "阿布纳达",
  "Sultan Al-Brake": "布雷克",
  "Haissem Hassan": "哈伊塞姆·哈桑",
  "Salah Zakaria": "萨拉赫·扎卡里亚",

  // 比利时补充
  "Hannes Delcroix": "德尔克鲁瓦",
  "Jean-Ricner Bellegarde": "贝尔加德",
  "Amad Diallo": "阿马德·迪亚罗",
  "Ange-Yoan Bonny": "博尼",
  "Jeremy Antonisse": "安东尼斯",
  "Francis De Vries": "德弗里斯",
  "Elye Wahi": "瓦伊",
  "Chadi Riad": "里亚德",
  "Ismael Saibari": "萨巴里",
  "Crysencio Summerville": "萨默维尔",

  // 埃及补充
  "Ahmed Fathi": "艾哈迈德·法蒂",
  "Ahmed Alaaeldin": "阿拉丁",
  "Hossam Abdelmaguid": "阿卜杜勒马吉德",
  "Tarek Alaa": "塔里克·阿拉",
  "Mohamed Alaa": "穆罕默德·阿拉",
  "Mahdi Soliman": "苏莱曼",

  // 沙特补充
  "Mohamed Touré": "穆罕默德·图雷",

  // 荷兰补充
  "Mats Wieffer": "韦弗",
  "Joshua Brenet": "约书亚·布雷内特",

  // 伊朗补充
  "Mahdi Torabi": "托拉比",

  // 巴拉圭补充
  "Yaimar Medina": "亚伊马尔·梅迪纳",
  "Gustavo Velázquez": "贝拉斯克斯",
  "José Canale": "坎纳莱",
  "Alexandro Maidana": "迈达纳",
  "Isidro Pitta": "皮塔",
  "Gonzalo Valle": "冈萨洛·巴耶",

  // 墨西哥补充
  "Ederson": "埃德尔森",
  "Luca Jaquez": "卢卡·哈克斯",
  "Gilberto Mora": "希尔伯托·莫拉",
  "Mateo Chávez": "马特奥·查韦斯",
  "Brahim Díaz": "布拉希姆·迪亚斯",

  // 苏格兰补充
  "Kieran Tierney": "凯尔·蒂尔尼",
  "Alfie Jones": "阿尔菲·琼斯",

  // 美国补充
  "Alexander Freeman": "亚历山大·弗里曼",
  "Lenny Joseph": "伦尼·约瑟夫",

  // 加拿大补充
  "Ime Okon": "伊梅·奥科恩",
  "Orlando Gill": "奥兰多·吉尔",
  "Bazoumana Touré": "巴祖马纳·图雷",

  // 波黑补充
  "Ajdin Hrustić": "鲁斯提奇",
  "Mladen Jurkas": "尤尔卡斯",
  "Paul Okon-Engstler": "奥孔-恩格斯特勒",

  // 新西兰补充
  "Bradley Cross": "布拉德利·克罗斯",
  "Jens Castrop": "卡斯特罗普",
  "Ricardo Adé": "里卡多·阿德",
  "Ricardo Goss": "里卡多·高斯",
  "John Yeboah": "约翰·耶博阿",

  // 库拉索补充
  "Wilson Isidor": "威尔逊·伊西多尔",

  // 佛得角补充
  "Wagner Pina": "瓦格纳·皮纳",
  "Yannick Semedo": "扬尼克·塞梅多",
  "Joaquin Seys": "霍阿金·塞斯",
  "Diego Moreira": "迭戈·莫雷拉",

  // 澳大利亚补充
  "Maximilian Arfsten": "马克西米利安·阿尔夫斯滕",
  "Christ Inao Oulaï": "克里斯特·乌莱",
  "Denil Castillo": "德尼尔·卡斯蒂略",

  // 科特迪瓦补充
  "Dennis Eckert Ayensa": "埃克特·阿延萨",

  // 摩洛哥补充
  "Joaquín Piquerez": "皮克雷斯",

  // 荷兰补充
  "Alessandro Circati": "奇尔卡提",

  // —— 主教练 ——
  "Graham Potter": "格雷厄姆·波特",
  "Sabri Lamouchi": "拉穆什",
  "Luis de la Fuente": "德拉富恩特",
  "Pedro Leitao Brito": "佩德罗·布里托",
  "Rudi Garcia": "鲁迪·加西亚",
  "Hossam Hassan": "侯萨姆·哈桑",
  "Georgios Donis": "多尼斯",
  "Marcelo Bielsa": "贝尔萨",

  // —— 裁判 ——
  "Yael Falcon Perez": "亚埃尔·法尔肯·佩雷斯",
  "Adham Mohammad": "阿达姆·穆罕默德",
  "Ramon Abatti Abel": "拉蒙·阿巴提·阿贝尔",
  "Maurizio Mariani": "毛里西奥·马里亚尼",
  "Jalal Jiyed": "贾拉尔·吉耶德",
  "Abdulrahman Al-Jassim": "阿卜杜勒拉赫曼·贾西姆",
  "Ivan Barton": "伊万·巴顿",
  "Alireza Faghani": "法加尼",
  "Clement Turpin": "克莱蒙·蒂尔潘",
  "Felix Brych": "菲利克斯·布里希",
  "Daniel Siebert": "丹尼尔·希贝尔特",
  "Bjorn Kuipers": "比昂·奎珀斯",
  "Wilmar Roldan": "威尔马·罗尔丹",
  "Victor Gomes": "维克多·戈麦斯",
  "Facundo Tello": "法昆多·泰洛",
  "Mehdi Mahdavikia": "马赫达维基亚",

  // ==== 2026-06 全量回填新增（6/11–6/16） ====

  // —— 主教练 ——
  "Javier Aguirre": "阿吉雷",
  "Hugo Broos": "布鲁斯",
  "Myung-Bo Hong": "洪明甫",
  "Miroslav Koubek": "库贝克",
  "Jesse Marsch": "马尔什",
  "Sergej Barbarez": "巴尔巴雷兹",
  "Mauricio Pochettino": "波切蒂诺",
  "Gustavo Alfaro": "阿尔法罗",
  "Julen Lopetegui": "洛佩特吉",
  "Murat Yakin": "亚金",
  "Carlo Ancelotti": "安切洛蒂",
  "Mohamed Ouahbi": "瓦赫比",
  "Sebastien Migne": "米涅",
  "Steve Clarke": "克拉克",
  "Tony Popovic": "波波维奇",
  "Vincenzo Montella": "蒙特拉",
  "Julian Nagelsmann": "纳格尔斯曼",
  "Dick Advocaat": "阿德沃卡特",
  "Ronald Koeman": "科曼",
  "Hajime Moriyasu": "森保一",
  "Emerse Fae": "法埃",
  "Sebastian Beccacece": "贝卡塞塞",
  "Amir Ghalenoei": "加莱诺伊",
  "D. Bazeley": "巴泽利",

  // —— 裁判 ——
  "Wilton Pereira Sampaio": "威尔顿·桑帕约",
  "Amin Mohamed Omar": "阿明·奥马尔",
  "Facundo Raul Tello Figueroa": "法昆多·泰洛",
  "Danny Makkelie": "马克利",
  "Said Martinez": "赛义德·马丁内斯",
  "Slavko Vinčić": "温契奇",
  "Mustapha Ghorbal": "古尔巴勒",
  "Jesús Valenzuela": "巴伦苏埃拉",
  "Jalal Jayed": "贾耶德",
  "Ismail Elfath": "埃尔法特",
  "François Letexier": "勒泰克谢",
  "César Ramos Palazuelos": "塞萨尔·拉莫斯",

  // —— 土耳其 ——
  "U. Cakir": "恰克尔",
  "Z. Celik": "切利克",
  "M. Demiral": "德米拉尔",
  "A. Bardakci": "巴尔达克奇",
  "F. Kadioglu": "卡德奥卢",
  "I. Yuksek": "于克塞克",
  "H. Calhanoglu": "恰尔汉奥卢",
  "A. Guler": "居莱尔",
  "O. Kokcu": "科库",
  "B. Yilmaz": "耶尔马兹",
  "K. Akturkoglu": "阿克蒂尔克奥卢",
  "M. Gunok": "居诺克",
  "A. Bayindir": "巴因德尔",
  "S. Akaydin": "阿卡伊登",
  "M. Muldur": "缪尔迪尔",
  "O. Kabak": "卡巴克",
  "Y. Akgun": "阿克君",
  "E. Elmali": "埃尔马勒",
  "D. Gul": "居尔",
  "K. Ayhan": "阿伊汗",
  "C. Soyuncu": "索因居",
  "I. Kahveci": "卡赫维奇",
  "S. Ozcan": "厄兹詹",
  "O. Aydin": "艾登",
  "K. Yildiz": "耶尔德兹",
  "C. Uzun": "乌准",

  // —— 澳大利亚 ——
  "P. Beach": "比奇",
  "J. Italiano": "伊塔利亚诺",
  "A. Circati": "奇尔卡蒂",
  "H. Souttar": "苏塔尔",
  "C. Burgess": "伯吉斯",
  "J. Bos": "博斯",
  "C. Metcalfe": "梅特卡夫",
  "A. O'Neill": "奥尼尔",
  "P. Okon-Engstler": "奥孔-恩斯特勒",
  "N. Irankunda": "伊兰昆达",
  "M. Toure": "图雷",
  "M. Ryan": "瑞安",
  "P. Izzo": "伊佐",
  "J. Geria": "杰里亚",
  "A. Mabil": "马比尔",
  "A. Hrustic": "赫鲁斯蒂奇",
  "K. Trewin": "特里温",
  "C. Volpato": "沃尔帕托",
  "M. Leckie": "莱基",
  "M. Degenek": "德格内克",
  "A. Behich": "贝希奇",
  "J. Irvine": "欧文",
  "C. Devlin": "德夫林",
  "T. Yengi": "延吉",
  "N. Velupillay": "韦卢皮莱",
  "L. Herrington": "赫林顿",

  // —— 摩洛哥 ——
  "A. Hakimi": "哈基米",
  "I. Diop": "迪奥普",
  "C. Riad": "里亚德",
  "N. Mazraoui": "马兹拉维",
  "N. El Aynaoui": "艾纳维",
  "A. Bouaddi": "布瓦迪",
  "B. Diaz": "布拉希姆·迪亚斯",
  "A. Ounahi": "乌纳希",
  "B. El Khannouss": "哈努斯",
  "I. Saibari": "萨伊巴里",
  "A. Tagnaouti": "塔格纳维提",
  "Munir": "穆尼尔",
  "S. Amrabat": "阿姆拉巴特",
  "A. El Kaabi": "凯比",
  "Y. Belammari": "贝拉马里",
  "A. Sbai": "斯巴伊",
  "C. Talbi": "塔尔比",
  "S. El Mourabet": "穆拉贝特",
  "G. Yassine": "亚辛",
  "M. Saadane": "萨阿达内",
  "S. Rahimi": "拉希米",
  "A. Salah-Eddine": "萨拉赫丁",
  "R. Halhal": "哈勒哈勒",
  "A. Amaimouni": "阿迈穆尼",
  "Z. El Ouahdi": "瓦赫迪",

  // —— 巴西 ——
  "Ibanez": "伊巴涅斯",
  "Gabriel": "加布里埃尔",
  "Bruno Guimaraes": "布鲁诺·吉马良斯",
  "Lucas Paqueta": "卢卡斯·帕奎塔",
  "Vinicius Junior": "维尼修斯",
  "I. Thiago": "蒂亚戈",
  "Leo Pereira": "莱奥·佩雷拉",
  "G. Martinelli": "马尔蒂内利",
  "M. Cunha": "库尼亚",

  // —— 波黑 ——
  "N. Vasilj": "瓦西利",
  "A. Dedic": "德迪奇",
  "N. Katic": "卡蒂奇",
  "T. Muharemovic": "穆哈雷莫维奇",
  "S. Kolasinac": "科拉希纳茨",
  "E. Bajraktarevic": "巴伊拉克塔雷维奇",
  "B. Tahirovic": "塔希罗维奇",
  "I. Basic": "巴希奇",
  "A. Memic": "梅米奇",
  "E. Demirovic": "德米罗维奇",
  "J. Lukic": "卢基奇",
  "M. Zlomislic": "兹洛米斯利奇",
  "M. Jurkas": "尤尔卡斯",
  "E. Dzeko": "哲科",
  "I. Sunjic": "孙吉奇",
  "E. Mahmic": "马赫米奇",
  "K. Alajbegovic": "阿拉伊贝戈维奇",
  "H. Tabakovic": "塔巴科维奇",
  "A. Hadziahmetovic": "哈季艾哈迈托维奇",
  "D. Hadzikadunic": "哈季卡杜尼奇",
  "D. Burnic": "布尔尼奇",
  "S. Radeljic": "拉德利奇",
  "N. Mujakic": "穆亚基奇",
  "A. Gigovic": "吉戈维奇",
  "S. Bazdar": "巴兹达尔",
  "A. Malic": "马利奇",

  // —— 加拿大 ——
  "M. Crepeau": "克雷波",
  "A. Johnston": "约翰斯顿",
  "L. De Fougerolles": "德富热罗勒",
  "D. Cornelius": "科尼利厄斯",
  "R. Laryea": "拉里亚",
  "T. Buchanan": "布坎南",
  "I. Kone": "科内",
  "S. Eustaquio": "尤斯塔基奥",
  "L. Millar": "米拉尔",
  "J. David": "戴维",
  "T. Oluwaseyi": "奥卢瓦塞伊",
  "D. St.Clair": "圣克莱尔",
  "O. Goodman": "古德曼",
  "C. Larin": "拉林",
  "J. Waterman": "沃特曼",
  "A. Davies": "戴维斯",
  "J. Shaffelburg": "沙费尔堡",
  "J. Nelson": "纳尔逊",
  "M. Bombito": "邦比托",
  "N. Sigur": "西古尔",
  "J. Osorio": "奥索里奥",
  "A. Jones": "琼斯",
  "M. Choiniere": "舒瓦尼耶",
  "N. Saliba": "萨利巴",
  "P. David": "戴维",
  "A. Ahmed": "艾哈迈德",

  // —— 厄瓜多尔 ——
  "H. Galindez": "加林德斯",
  "A. Franco": "弗兰科",
  "J. Ordonez": "奥多涅斯",
  "W. Pacho": "帕乔",
  "P. Hincapie": "因卡皮耶",
  "J. Yeboah": "耶博阿",
  "M. Caicedo": "凯塞多",
  "P. Vite": "维特",
  "A. Minda": "明达",
  "G. Plata": "普拉塔",
  "E. Valencia": "埃内尔·巴伦西亚",
  "G. Valle": "巴列",
  "M. Ramirez": "拉米雷斯",
  "P. Estupinan": "埃斯图皮尼安",
  "J. Caicedo": "凯塞多",
  "A. Preciado": "普雷西亚多",
  "A. Valencia": "安赫尔·巴伦西亚",
  "N. Angulo": "安古洛",
  "K. Rodriguez": "罗德里格斯",
  "F. Torres": "托雷斯",
  "J. Porozo": "波罗索",
  "J. Alcivar": "阿尔西瓦尔",
  "D. Castillo": "卡斯蒂略",
  "Y. Medina": "梅迪纳",
  "J. Arevalo": "阿雷瓦洛",
  "K. Paez": "帕埃斯",

  // —— 科特迪瓦 ——
  "Y. Fofana": "约翰·福法纳",
  "G. Doue": "杜埃",
  "W. Singo": "辛戈",
  "E. Agbadou": "阿格巴杜",
  "G. Konan": "科南",
  "Y. Diomande": "迪奥曼德",
  "F. Kessie": "凯西",
  "S. Fofana": "塞科·福法纳",
  "B. Toure": "图雷",
  "N. Pepe": "佩佩",
  "E. Wahi": "瓦希",
  "M. Kone": "科内",
  "A. Lafont": "拉丰",
  "J. Seri": "塞里",
  "I. Sangare": "桑加雷",
  "E. Ndicka": "恩迪卡",
  "C. Operi": "奥佩里",
  "O. Diomande": "奥迪隆·迪奥曼德",
  "O. Kossounou": "科苏努",
  "E. Guessand": "盖桑",
  "A. Diallo": "迪亚洛",
  "P. Guiagon": "吉亚贡",
  "S. Adingra": "阿丁格拉",
  "A. Bonny": "邦尼",
  "O. Diakite": "迪亚基特",
  "C. Inao Oulai": "乌莱",

  // —— 西班牙 ——
  "Victor Muñoz": "维克多·穆尼奥斯",

  // —— 库拉索 ——
  "E. Room": "鲁姆",
  "S. Floranus": "弗洛拉努斯",
  "R. Bazoer": "巴祖尔",
  "A. Obispo": "奥比斯波",
  "D. Fonville": "丰维尔",
  "L. Comenencia": "科梅嫩西亚",
  "L. Bacuna": "莱安德罗·巴库纳",
  "J. Bacuna": "尤埃尔·巴库纳",
  "T. Chong": "钟",
  "J. Locadia": "洛卡迪亚",
  "S. Hansen": "汉森",
  "T. Doornbusch": "多恩布施",
  "T. Bodak": "博达克",
  "B. Kuwas": "库瓦斯",
  "K. Gorre": "戈雷",
  "K. Felida": "费利达",
  "R. van Eijma": "范艾伊马",
  "J. Antonisse": "安东尼斯",
  "A. Martha": "马尔塔",
  "T. Noslin": "诺斯林",
  "J. Margaritha": "马加里塔",
  "J. Brenet": "布雷内特",
  "G. Kastaneer": "卡斯塔尼尔",
  "G. Roemeratoe": "鲁梅拉托",
  "J. Gaari": "加里",
  "S. Sambo": "桑博",

  // —— 德国 ——
  "M. Neuer": "诺伊尔",
  "J. Kimmich": "基米希",
  "J. Tah": "塔",
  "N. Schlotterbeck": "施洛特贝克",
  "N. Brown": "布朗",
  "F. Nmecha": "恩梅查",
  "A. Pavlovic": "帕夫洛维奇",
  "L. Sane": "萨内",
  "J. Musiala": "穆夏拉",
  "F. Wirtz": "维尔茨",
  "K. Havertz": "哈弗茨",
  "O. Baumann": "鲍曼",
  "A. Nubel": "纽贝尔",
  "P. Gross": "格罗斯",
  "L. Goretzka": "戈雷茨卡",
  "A. Rudiger": "吕迪格",
  "N. Amiri": "阿米里",
  "M. Beier": "拜尔",
  "M. Thiaw": "蒂奥",
  "N. Woltemade": "沃尔特马德",
  "J. Leweling": "莱韦林",
  "W. Anton": "安东",
  "D. Undav": "温达夫",
  "D. Raum": "劳姆",
  "A. Stiller": "施蒂勒",
  "A. Ouedraogo": "乌埃德拉奥戈",

  // —— 苏格兰 ——
  "A. Gunn": "冈恩",
  "A. Hickey": "希基",
  "G. Hanley": "汉利",
  "J. Hendry": "亨德里",
  "A. Robertson": "罗伯逊",
  "B. Gannon-Doak": "甘农-多克",
  "S. McTominay": "麦克托米奈",
  "L. Ferguson": "弗格森",
  "J. McGinn": "麦金",
  "L. Shankland": "尚克兰",
  "C. Adams": "亚当斯",
  "C. Gordon": "戈登",
  "L. Kelly": "凯利",
  "K. McLean": "麦克林",
  "J. Souttar": "苏塔尔",
  "R. Christie": "克里斯蒂",
  "K. Tierney": "蒂尔尼",
  "A. Ralston": "拉尔斯顿",
  "L. Dykes": "戴克斯",
  "N. Patterson": "帕特森",
  "S. McKenna": "麦肯纳",
  "D. Hyam": "海厄姆",
  "G. Hirst": "赫斯特",
  "R. Stewart": "斯图尔特",
  "T. Fletcher": "弗莱彻",
  "F. Curtis": "柯蒂斯",

  // —— 海地 ——
  "J. Placide": "普拉西德",
  "C. Arcus": "阿尔库斯",
  "R. Ade": "阿德",
  "H. Delcroix": "德尔克鲁瓦",
  "M. Experience": "埃克斯佩里安斯",
  "L. Deedson": "迪德森",
  "D. Jean Jacques": "让·雅克",
  "J. Bellegarde": "贝勒加德",
  "R. Providence": "普罗维登斯",
  "F. Pierrot": "皮埃罗",
  "W. Isidor": "伊西多尔",
  "J. Duverger": "迪韦尔热",
  "A. Pierre": "皮埃尔",
  "D. Lacroix": "拉克鲁瓦",
  "D. Nazon": "纳宗",
  "D. Etienne": "艾蒂安",
  "J. Duverne": "迪韦尔讷",
  "C. Sainte": "圣特",
  "J. Casimir": "卡西米尔",
  "L. Joseph": "约瑟夫",
  "G. Metusala": "梅图萨拉",
  "D. Simon": "西蒙",
  "W. Pierre": "皮埃尔",
  "K. Thermoncy": "泰尔蒙西",
  "Y. Fortune": "福蒂内",
  "W. Paugain": "波甘",

  // —— 捷克 ——
  "M. Kovar": "科瓦日",
  "S. Chaloupek": "哈洛佩克",
  "R. Hranac": "赫拉纳奇",
  "L. Krejci": "克雷伊奇",
  "V. Coufal": "曹法尔",
  "T. Soucek": "索切克",
  "A. Sojka": "索伊卡",
  "J. Zeleny": "泽莱尼",
  "L. Provod": "普罗沃德",
  "P. Sulc": "舒尔茨",
  "P. Schick": "希克",
  "J. Stanek": "斯塔涅克",
  "L. Hornicek": "霍尔尼切克",
  "T. Holes": "霍莱什",
  "J. Kuchta": "库赫塔",
  "D. Doudera": "杜德拉",
  "D. Zima": "齐马",
  "D. Jurasek": "尤拉塞克",
  "A. Hlozek": "赫洛热克",
  "L. Cerv": "切尔夫",
  "D. Visinsky": "维辛斯基",
  "V. Darida": "达里达",
  "T. Chory": "霍里",
  "M. Sadilek": "萨迪莱克",
  "M. Chytil": "希蒂尔",
  "H. Sochurek": "索胡雷克",

  // —— 韩国 ——
  "Kim Seung-Gyu": "金承奎",
  "Lee Han-Beom": "李韩范",
  "Kim Min-Jae": "金玟哉",
  "Lee Gi-Hyuk": "李起赫",
  "Seol Young-Woo": "薛英祐",
  "Hwang In-Beom": "黄仁范",
  "Paik Seung-Ho": "白升浩",
  "Lee Tae-Seok": "李泰锡",
  "Lee Kang-In": "李刚仁",
  "Lee Jae-Sung": "李在城",
  "Son Heung-Min": "孙兴慜",
  "Jo Hyeon-Woo": "赵贤祐",
  "Song Bum-Keun": "宋范根",
  "Hwang Hee-Chan": "黄喜灿",
  "Kim Jin-Gyu": "金镇圭",
  "Park Jin-Seob": "朴镇燮",
  "Lee Dong-Gyeong": "李东炅",
  "Cho Gue-Sung": "赵圭成",
  "Oh Hyeon-Gyu": "吴贤揆",
  "Eom Ji-Sung": "严志诚",
  "J. Castrop": "卡斯特罗普",
  "Kim Moon-Hwan": "金文奂",
  "Kim Tae-Hyeon": "金泰显",
  "Bae Jun-Ho": "裴俊浩",
  "Cho Wi-Je": "赵威霁",

  // —— 南非 ——
  "R. Williams": "威廉姆斯",
  "K. Mudau": "穆达乌",
  "N. Sibisi": "西比西",
  "I. Okon": "奥孔",
  "M. Mbokazi": "姆博卡齐",
  "A. Modiba": "莫迪巴",
  "T. Mokoena": "莫科埃纳",
  "Y. Sithole": "西托莱",
  "J. Adams": "亚当斯",
  "I. Rayners": "雷纳斯",
  "L. Foster": "福斯特",
  "R. Goss": "戈斯",
  "S. Chaine": "沙因",
  "B. Cross": "克罗斯",
  "T. Mbatha": "姆巴塔",
  "E. Makgopa": "马克戈帕",
  "T. Matuludi": "马图卢迪",
  "K. Ndamane": "恩达马内",
  "T. Zwane": "兹瓦内",
  "O. Appollis": "阿波利斯",
  "T. Moremi": "莫雷米",
  "T. Maseko": "马塞科",
  "K. Sebelebele": "塞贝莱贝莱",
  "O. Makhanya": "马卡尼亚",
  "R. Mofokeng": "莫福肯",
  "S. Kabini": "卡比尼",

  // —— 墨西哥 ——
  "R. Rangel": "兰赫尔",
  "I. Reyes": "雷耶斯",
  "C. Montes": "蒙特斯",
  "J. Vasquez": "巴斯克斯",
  "J. Gallardo": "加亚尔多",
  "E. Lira": "利拉",
  "R. Alvarado": "阿尔瓦拉多",
  "B. Gutierrez": "古铁雷斯",
  "A. Fidalgo": "菲达尔戈",
  "J. Quinones": "基尼奥内斯",
  "R. Jimenez": "拉乌尔·希门尼斯",
  "G. Ochoa": "奥乔亚",
  "C. Acevedo": "阿塞韦多",
  "G. Martinez": "马丁内斯",
  "L. Chavez": "路易斯·查韦斯",
  "O. Vargas": "巴尔加斯",
  "M. Chavez Garcia": "查韦斯·加西亚",
  "O. Pineda": "皮内达",
  "A. Vega": "贝加",
  "J. Sanchez": "桑切斯",
  "E. Alvarez": "埃德松·阿尔瓦雷斯",
  "S. Gimenez": "希门尼斯",
  "C. S. Huerta Valera": "韦尔塔",
  "L. Romo": "罗莫",
  "A. Gonzalez": "冈萨雷斯",
  "G. Mora": "莫拉",

  // —— 日本 ——
  "Z. Suzuki": "铃木彩艳",
  "T. Watanabe": "渡边刚",
  "S. Taniguchi": "谷口彰悟",
  "H. Ito": "伊藤洋辉",
  "R. Doan": "堂安律",
  "K. Sano": "佐野海舟",
  "D. Kamada": "镰田大地",
  "K. Nakamura": "中村敬斗",
  "T. Kubo": "久保建英",
  "D. Maeda": "前田大然",
  "A. Ueda": "上田绮世",
  "K. Osako": "大迫敬介",
  "T. Hayakawa": "早川友基",
  "Y. Nagatomo": "长友佑都",
  "K. Itakura": "板仓滉",
  "T. Tomiyasu": "富安健洋",
  "A. Seko": "濑古步梦",
  "Y. Sugawara": "菅原由势",
  "S. Machino": "町野修斗",
  "Y. Suzuki": "铃木唯人",
  "J. Suzuki": "铃木淳之介",
  "K. Goto": "后藤启介",
  "J. Ito": "伊东纯也",
  "K. Ogawa": "小川航基",
  "A. Tanaka": "田中碧",
  "K. Shiogai": "盐贝健人",

  // —— 荷兰 ——
  "B. Verbruggen": "费尔布鲁根",
  "D. Dumfries": "邓弗里斯",
  "J. P. van Hecke": "范赫克",
  "V. van Dijk": "范戴克",
  "M. van de Ven": "范德文",
  "R. Gravenberch": "格拉文贝赫",
  "F. de Jong": "德容",
  "T. Reijnders": "雷因德斯",
  "C. Summerville": "萨默维尔",
  "D. Malen": "马伦",
  "C. Gakpo": "加克波",
  "M. Flekken": "弗莱肯",
  "R. Roefs": "鲁夫斯",
  "M. Depay": "德佩",
  "W. Weghorst": "韦霍斯特",
  "Q. Timber": "廷伯",
  "B. Brobbey": "布罗贝",
  "M. Wieffer": "维弗",
  "M. De Roon": "德龙",
  "N. Ake": "阿克",
  "T. Koopmeiners": "库普梅纳斯",
  "J. Kluivert": "克鲁伊维特",
  "G. Til": "蒂尔",
  "N. Lang": "朗",
  "L. Geertruida": "海尔特勒伊达",
  "J. Hato": "哈托",

  // —— 卡塔尔 ——
  "M. Abunada": "阿布纳达",
  "A. Al Oui": "阿勒奥伊",
  "B. Khoukhi": "胡希",
  "H. Al Amin": "阿勒阿明",
  "J. Gaber": "贾比尔",
  "A. O. Madibo": "马迪博",
  "I. Laye": "拉耶",
  "Y. Abdurisag": "阿卜杜里萨格",
  "A. Afif": "阿菲夫",
  "S. Zakaria": "扎卡里亚",
  "M. Barsham": "巴尔沙姆",
  "H. Al Haydos": "阿勒海多斯",
  "M. Muntari": "蒙塔里",
  "A. Al Hussain": "阿勒侯赛因",
  "A. Hatem": "哈特姆",
  "A. Ali": "阿里",
  "A. Fathi": "法蒂",
  "T. Jamshid": "贾姆希德",
  "K. Boudiaf": "布迪亚夫",
  "A. Alaaeldin": "阿拉丁",
  "S. Al Brake": "阿勒布拉克",
  "A. Al Ganehi": "阿勒加内希",
  "M. Al Mannai": "阿勒曼奈",

  // —— 突尼斯（补充缩写形式） ——
  "A. Chamakh": "沙马赫",
  "M. Talbi": "塔尔比",
  "M. Ben Hamida": "本·哈米达",
  "A. Abdi": "阿卜迪",
  "S. Ben Hessen": "本·赫森",
  "A. Dahmen": "达赫门",
  "M. Neffati": "内法蒂",
  "K. Ayari": "阿亚里",
  "R. Chikhaoui": "希哈维",
  "R. Elloumi": "埃卢米",
  "M. Ben Ouanes": "本·瓦内斯",
  "D. Bronn": "布龙",
  "H. Mastouri": "马斯图里",
  "A. Arous": "阿鲁斯",

  // —— 瑞典（补充缩写形式） ——
  "K. Nordfeldt": "努德费尔特",
  "G. Lagerbielke": "拉格尔别尔克",
  "I. Hien": "希恩",
  "V. Lindelof": "林德洛夫",
  "V. Gyökeres": "约克雷斯",
  "J. Widell Zetterstrom": "塞特斯特伦",
  "V. Johansson": "维克托·约翰松",
  "C. Starfelt": "斯塔费尔特",
  "G. Nilsson": "尼尔松",
  "H. Johansson": "约翰松",
  "T. Ali": "阿里",
  "K. Sema": "塞马",
  "E. Smith": "史密斯",
  "H. Ekdal": "埃克达尔",
  "B. Zeneli": "泽内利",

  // —— 巴拉圭 ——
  "O. Gill": "希尔",
  "J. Caceres": "卡塞雷斯",
  "G. Gomez": "古斯塔沃·戈麦斯",
  "O. Alderete": "阿尔德雷特",
  "J. Alonso": "阿隆索",
  "D. Gomez": "迭戈·戈麦斯",
  "A. Cubas": "库巴斯",
  "D. Bobadilla": "博瓦迪利亚",
  "M. Almiron": "阿尔米隆",
  "A. Sanabria": "萨纳夫里亚",
  "J. Enciso": "恩西索",
  "R. Fernandez": "费尔南德斯",
  "G. Olveira": "奥尔韦拉",
  "G. Velazquez": "贝拉斯克斯",
  "Fabian Balbuena": "巴尔布埃纳",
  "G. Avalos": "阿瓦洛斯",
  "G. Caballero": "卡瓦列罗",
  "J. Canale": "卡纳莱",
  "I. Pitta": "皮塔",
  "M. Galarza": "加拉萨",
  "R. Sosa": "索萨",
  "Kaku": "卡库",
  "A. Arce": "阿尔塞",
  "B. Ojeda": "奥赫达",
  "A. Maidana": "马伊达纳",

  // —— 美国 ——
  "M. Freese": "弗里斯",
  "A. Freeman": "弗里曼",
  "C. Richards": "理查兹",
  "T. Ream": "里姆",
  "A. Robinson": "安东尼·罗宾逊",
  "T. Adams": "亚当斯",
  "M. Tillman": "蒂尔曼",
  "S. Dest": "德斯特",
  "W. McKennie": "麦肯尼",
  "C. Pulisic": "普利西奇",
  "F. Balogun": "巴洛贡",
  "C. Brady": "布雷迪",
  "M. Turner": "特纳",
  "A. Trusty": "特拉斯蒂",
  "R. Pepi": "佩皮",
  "G. Reyna": "雷纳",
  "S. Berhalter": "贝哈尔特",
  "H. Wright": "赖特",
  "C. Roldan": "罗尔丹",
  "A. Zendejas": "森德哈斯",
  "T. Weah": "韦阿",
  "M. Robinson": "迈尔斯·罗宾逊",
  "B. Aaronson": "阿伦森",
  "M. McKenzie": "麦肯齐",
  "J. Scally": "斯卡利",
  "M. Arfsten": "阿夫斯滕",

  // —— 瑞士 ——
  "G. Kobel": "科贝尔",
  "D. Zakaria": "扎卡里亚",
  "N. Elvedi": "埃尔维迪",
  "M. Akanji": "阿坎吉",
  "R. Rodriguez": "里卡多·罗德里格斯",
  "M. Aebischer": "埃比舍尔",
  "G. Xhaka": "扎卡",
  "R. Freuler": "弗罗伊勒",
  "D. Ndoye": "恩多耶",
  "B. Embolo": "恩博洛",
  "R. Vargas": "鲁本·巴尔加斯",
  "Y. Mvogo": "姆沃戈",
  "M. Keller": "凯勒",
  "S. Widmer": "维德默",
  "D. Sow": "索",
  "N. Okafor": "奥卡福",
  "E. Comert": "科默特",
  "C. Itten": "伊滕",
  "C. Fassnacht": "法斯纳赫特",
  "M. Muheim": "穆海姆",
  "F. Rieder": "里德",
  "A. Amenda": "阿门达",
  "Z. Amdouni": "阿姆杜尼",
  "A. Jashari": "亚沙里",
  "L. Jaquez": "雅克斯",
  "J. Manzambi": "曼赞比",

  // —— 事件补充（伊朗/新西兰/南非缩写形式） ——
  "Siphephelo Sithole": "西托莱",
  "E. Just": "尤斯特",
  "C. Wood": "克里斯·伍德",
  "R. Rezaeian": "雷扎伊安",
  "A. Yousefi": "优素菲",
  "M. Ghaedi": "加埃迪",
  "S. Moghanlou": "莫甘卢",
  "A. Alipour": "阿里普尔",
  "M. Mohebi": "莫赫比",
  "S. Ghoddos": "戈多斯",
  "E. Hajsafi": "哈吉萨菲",
  "L. Cacace": "卡卡切",
  "B. Old": "奥尔德",
  "C. McCowatt": "麦考瓦特",
  "R. Thomas": "罗里·托马斯",
  "T. Payne": "佩恩",
  "C. Elliot": "埃利奥特",
  "M. Taremi": "塔雷米",
  "A. Hosseinzadeh": "侯赛因扎德",
  "S. Singh": "辛格",
  "J. Randall": "兰德尔",
  "M. Stamenic": "斯塔梅尼奇",
  "T. Bindon": "宾登",

  // —— 法国 ——
  "Didier Deschamps": "德尚",
  "Mike Maignan": "迈尼昂",
  "Jules Koundé": "孔德",
  "J. Kounde": "孔德",
  "William Saliba": "萨利巴",
  "W. Saliba": "萨利巴",
  "Dayot Upamecano": "于帕梅卡诺",
  "D. Upamecano": "于帕梅卡诺",
  "Theo Hernández": "特奥·埃尔南德斯",
  "T. Hernandez": "特奥·埃尔南德斯",
  "Aurélien Tchouaméni": "琼阿梅尼",
  "A. Tchouameni": "琼阿梅尼",
  "Adrien Rabiot": "拉比奥",
  "A. Rabiot": "拉比奥",
  "Michael Olise": "奥利塞",
  "M. Olise": "奥利塞",
  "Ousmane Dembélé": "登贝莱",
  "O. Dembele": "登贝莱",
  "Désiré Doué": "杜埃",
  "D. Doue": "杜埃",
  "Kylian Mbappé": "姆巴佩",
  "K. Mbappe": "姆巴佩",
  "Brice Samba": "桑巴",
  "Robin Risser": "里塞",
  "Maxence Lacroix": "拉克鲁瓦",
  "Lucas Hernández": "卢卡斯·埃尔南德斯",
  "L. Hernandez": "卢卡斯·埃尔南德斯",
  "Lucas Digne": "迪涅",
  "L. Digne": "迪涅",
  "Ibrahima Konaté": "科纳特",
  "I. Konate": "科纳特",
  "Malo Gusto": "古斯托",
  "M. Gusto": "古斯托",
  "Manu Koné": "马努·科内",
  // 注：缩写 "M. Kone" 与科特迪瓦球员撞名，已在上文映射为「科内」，此处不重复
  "N'Golo Kanté": "坎特",
  "N. Kante": "坎特",
  "Rayan Cherki": "谢尔基",
  "R. Cherki": "谢尔基",
  "Warren Zaïre-Emery": "扎伊尔-埃梅里",
  "W. Zaire-Emery": "扎伊尔-埃梅里",
  "Maghnes Akliouche": "阿克利乌什",
  "M. Akliouche": "阿克利乌什",
  "Marcus Thuram": "马库斯·图拉姆",
  "M. Thuram": "马库斯·图拉姆",
  "Jean-Philippe Mateta": "马特塔",
  "J. Mateta": "马特塔",
  "Bradley Barcola": "巴尔科拉",
  "B. Barcola": "巴尔科拉",

  // —— 塞内加尔 ——
  "Bouna Thiaw Pape": "布纳·蒂奥",
  "Edouard Mendy": "爱德华·门迪",
  "E. Mendy": "爱德华·门迪",
  "Krépin Diatta": "迪亚塔",
  "K. Diatta": "迪亚塔",
  "Kalidou Koulibaly": "库利巴利",
  "K. Koulibaly": "库利巴利",
  "Moussa Niakhaté": "尼亚卡特",
  "M. Niakhate": "尼亚卡特",
  "El Hadji Malick Diouf": "马利克·迪乌夫",
  "E. Diouf": "马利克·迪乌夫",
  "Lamine Camara": "拉明·卡马拉",
  "L. Camara": "拉明·卡马拉",
  "Idrissa Gana Gueye": "伊德里萨·盖耶",
  "I. Gueye": "伊德里萨·盖耶",
  "Pape Gueye": "帕普·盖耶",
  "P. Gueye": "帕普·盖耶",
  "Ismaïla Sarr": "伊斯马伊拉·萨尔",
  "I. Sarr": "伊斯马伊拉·萨尔",
  "Nicolas Jackson": "尼古拉斯·杰克逊",
  "N. Jackson": "尼古拉斯·杰克逊",
  "Sadio Mané": "马内",
  "S. Mane": "马内",
  "Yehvann Diouf": "耶万·迪乌夫",
  "Mory Diaw": "迪奥",
  "Ismail Jakobs": "雅各布斯",
  "I. Jakobs": "雅各布斯",
  "Antoine Mendy": "安托万·门迪",
  "A. Mendy": "安托万·门迪",
  "Mamadou Sarr": "马马杜·萨尔",
  "Abdoulaye Seck": "塞克",
  "A. Seck": "塞克",
  "Pape Matar Sarr": "帕普·马塔尔·萨尔",
  "P. Sarr": "帕普·马塔尔·萨尔",
  "Pathé Ismaël Ciss": "西斯",
  "P. Ciss": "西斯",
  "Iliman Ndiaye": "伊利曼·恩迪亚耶",
  "I. Ndiaye": "伊利曼·恩迪亚耶",
  "Habib Diarra": "迪亚拉",
  "H. Diarra": "迪亚拉",
  "Bara Sapoko Ndiaye": "巴拉·恩迪亚耶",
  "Cherif Ndiaye": "谢里夫·恩迪亚耶",
  "C. Ndiaye": "谢里夫·恩迪亚耶",
  "Assane Diao": "迪奥",
  "A. Diao": "迪奥",
  "Ibrahim Mbaye": "姆巴耶",
  "I. Mbaye": "姆巴耶",
  "Ahmadou Bamba Dieng": "迪昂",
  "B. Dieng": "迪昂",
  // —— 2026-06-18 补译：POR-COD/ARG-ALG/AUT-JOR/IRQ-NOR 等新入库场次的球员/教练/裁判 ——
  "Lionel Messi": "梅西",
  "L. Messi": "梅西",
  "Lautaro Martínez": "劳塔罗·马丁内斯",
  "L. Martinez": "劳塔罗·马丁内斯",
  "Lisandro Martínez": "里桑德罗·马丁内斯",
  "Cristian Romero": "克里斯蒂安·罗梅罗",
  "C. Romero": "克里斯蒂安·罗梅罗",
  "Nicolás Otamendi": "奥塔门迪",
  "N. Otamendi": "奥塔门迪",
  "Gonzalo Montiel": "蒙铁尔",
  "G. Montiel": "蒙铁尔",
  "Nahuel Molina": "莫利纳",
  "N. Molina": "莫利纳",
  "Rodrigo De Paul": "德保罗",
  "R. de Paul": "德保罗",
  "Alexis Mac Allister": "麦卡利斯特",
  "Enzo Fernández": "恩佐·费尔南德斯",
  "Thiago Almada": "阿尔马达",
  "T. Almada": "阿尔马达",
  "Facundo Medina": "梅迪纳",
  "Julián Álvarez": "胡利安·阿尔瓦雷斯",
  "J. Alvarez": "胡利安·阿尔瓦雷斯",
  "Nicolás González": "尼古拉斯·冈萨雷斯",
  "N. Gonzalez": "尼古拉斯·冈萨雷斯",
  "Nico Paz": "尼科·帕斯",
  "N. Paz": "尼科·帕斯",
  "Cristiano Ronaldo": "C罗",
  "C. Ronaldo": "C罗",
  "Bruno Fernandes": "B费尔南德斯",
  "B. Fernandes": "B费尔南德斯",
  "Bernardo Silva": "B席尔瓦",
  "B. Silva": "B席尔瓦",
  "Vitinha": "维蒂尼亚",
  "João Neves": "若昂·内维斯",
  "J. Neves": "若昂·内维斯",
  "João Cancelo": "坎塞洛",
  "J. Cancelo": "坎塞洛",
  "Nuno Mendes": "努诺·门德斯",
  "N. Mendes": "努诺·门德斯",
  "Pedro Neto": "佩德罗·内托",
  "P. Neto": "佩德罗·内托",
  "Diogo Costa": "迪奥戈·科斯塔",
  "Renato Veiga": "雷纳托·维加",
  "Tomás Araújo": "托马斯·阿劳若",
  "Lionel Mpasi Nzau": "姆帕西",
  "Aaron Wan-Bissaka": "万-比萨卡",
  "Chancel Mbemba": "姆本巴",
  "Axel Tuanzebe": "图安泽贝",
  "Steve Kapuadi": "卡普阿迪",
  "Arthur Masuaku": "马苏阿库",
  "Samuel Moutoussamy": "穆图萨米",
  "Ngal'ayel Mukau": "穆考",
  "Edo Kayembe": "卡延贝",
  "Cédric Bakambu": "巴坎布",
  "Yoane Wissa": "维萨",
  "Erling Haaland": "哈兰德",
  "E. Haaland": "哈兰德",
  "Martin Ødegaard": "厄德高",
  "M. Odegaard": "厄德高",
  "Alexander Sørloth": "瑟尔洛特",
  "A. Sorloth": "瑟尔洛特",
  "Antonio Nusa": "努萨",
  "A. Nusa": "努萨",
  "Fredrik Aursnes": "奥尔斯内斯",
  "F. Aursnes": "奥尔斯内斯",
  "Sander Berge": "贝里",
  "P. Berg": "贝里",
  "Kristoffer Ajer": "阿耶尔",
  "Julian Ryerson": "里尔森",
  "Torbjørn Heggem": "海格姆",
  "David Møller Wolfe": "沃尔夫",
  "D. Wolfe": "沃尔夫",
  "Ørjan Nyland": "尼兰",
  "Leo Østigård": "厄斯蒂高",
  "L. Ostigard": "厄斯蒂高",
  "Oscar Bobb": "博布",
  "O. Bobb": "博布",
  "Patrick Berg": "帕特里克·贝里",
  "Kristian Thorstvedt": "托尔斯特维特",
  "K. Thorstvedt": "托尔斯特维特",
  "Antonio Schjelderup": "舍尔德鲁普",
  "A. Schjelderup": "舍尔德鲁普",
  "Patrik Wimmer": "维默",
  "P. Wimmer": "维默",
  "Alexander Schlager": "施拉格",
  "David Alaba": "阿拉巴",
  "D. Alaba": "阿拉巴",
  "Marcel Sabitzer": "扎比策",
  "M. Sabitzer": "扎比策",
  "Konrad Laimer": "莱默尔",
  "Nicolas Seiwald": "赛瓦尔德",
  "Romano Schmid": "施密德",
  "R. Schmid": "施密德",
  "Philipp Lienhart": "利恩哈特",
  "Stefan Posch": "波施",
  "Phillipp Mwene": "姆韦内",
  "P. Mwene": "姆韦内",
  "Xaver Schlager": "夏沃·施拉格",
  "X. Schlager": "夏沃·施拉格",
  "Saša Kalajdžić": "卡拉伊季奇",
  "S. Kalajdzic": "卡拉伊季奇",
  "Marko Arnautović": "阿瑙托维奇",
  "M. Arnautovic": "阿瑙托维奇",
  "Konrad Danso": "丹索",
  "K. Danso": "丹索",
  "Paul Wanner": "瓦纳",
  "P. Wanner": "瓦纳",
  "Aïssa Mandi": "曼迪",
  "Ramy Bensebaini": "本塞拜尼",
  "Rayan Aït-Nouri": "艾特-努里",
  "Hicham Boudaoui": "布达维",
  "H. Boudaoui": "布达维",
  "Nabil Bentaleb": "本塔莱布",
  "N. Bentaleb": "本塔莱布",
  "Amine Gouiri": "古伊里",
  "A. Gouiri": "古伊里",
  "Anis Hadj Moussa": "哈吉·穆萨",
  "A. Hadj Moussa": "哈吉·穆萨",
  "Farès Chaïbi": "沙伊比",
  "F. Chaibi": "沙伊比",
  "Ibrahim Maza": "马扎",
  "I. Maza": "马扎",
  "Rafik Belghali": "贝勒加利",
  "Riyad Mahrez": "马赫雷斯",
  "R. Mahrez": "马赫雷斯",
  "Mohamed Amoura": "阿穆拉",
  "M. Amoura": "阿穆拉",
  "Ramiz Zerrouki": "泽鲁基",
  "R. Zerrouki": "泽鲁基",
  "Hicham Aouar": "阿瓦尔",
  "H. Aouar": "阿瓦尔",
  "Adam Boulbina": "布勒比纳",
  "A. Boulbina": "布勒比纳",
  "Mohamed Farji": "法尔吉",
  "M. Farji": "法尔吉",
  "Jalal Hassan": "贾拉勒·哈桑",
  "Merchas Doski": "多斯基",
  "Akam Hashem": "哈希姆",
  "Hussein Ali": "侯赛因·阿里",
  "H. Ali": "侯赛因·阿里",
  "Aymen Hussein": "艾曼·侯赛因",
  "A. Hussein": "艾曼·侯赛因",
  "Ali Jasim": "阿里·贾西姆",
  "A. Jasim": "阿里·贾西姆",
  "Ibrahim Bayesh": "巴耶什",
  "I. Bayesh": "巴耶什",
  "Zaid Tahseen": "扎伊德·塔赫辛",
  "Z. Tahseen": "扎伊德·塔赫辛",
  "Zaid Ismail": "扎伊德·伊斯梅尔",
  "Z. Ismaeel": "扎伊德·伊斯梅尔",
  "Ehsan Haddad": "哈达德",
  "E. Haddad": "哈达德",
  "Mohannad Abu Taha": "阿布·塔哈",
  "Manaf Saadoon": "萨敦",
  "M. Saadoon": "萨敦",
  "Sajjad Obaid": "奥贝德",
  "S. Obaid": "奥贝德",
  "Ali Al-Hamadi": "哈马迪",
  "A. Al Hamadi": "哈马迪",
  "Abdallah Nasib": "纳西卜",
  "A. Nasib": "纳西卜",
  "Yazan Al-Arab": "亚赞·阿拉伯",
  "Y. Al Arab": "亚赞·阿拉伯",
  "Mo Abualnadi": "阿布纳迪",
  "M. Abualnadi": "阿布纳迪",
  "Noor Al-Deen Al Rawabdeh": "拉瓦布德",
  "N. Al Rawabdeh": "拉瓦布德",
  "Odeh Fakhoury": "法胡里",
  "O. Al Fakhouri": "法胡里",
  "Yazeed Abu Laila": "阿布·莱拉",
  "Mousa Tamari": "塔马里",
  "M. Tamari": "塔马里",
  "Ali Olwan": "奥尔万",
  "A. Olwan": "奥尔万",
  "Nizar Al-Rashdan": "尼扎尔·拉什丹",
  "Amir Al-Ammari": "阿米尔·阿马里",
  "A. Al Ammari": "阿米尔·阿马里",
  "Mahmoud Al-Mardi": "马尔迪",
  "M. Al Mardi": "马尔迪",
  "Saleh Rateb": "罗桑",
  "S. Al Rosan": "罗桑",
  "Yazan Al-Naimat": "奈马特",
  "Y. Al Naimat": "奈马特",
  "Mahmoud Al-Daoud": "达伍德",
  "M. Al Daoud": "达伍德",
  "Ahmad Azaizeh": "阿扎泽",
  "A. Azaizeh": "阿扎泽",
  "Ali Qasem": "卡西姆",
  "A. Qasem": "卡西姆",
  "Carney Chukwuemeka": "丘克伍埃梅卡",
  "C. Chukwuemeka": "丘克伍埃梅卡",
  "Zidane Iqbal": "扎伊丹·伊克巴尔",
  "Z. Iqbal": "扎伊丹·伊克巴尔",
  "Luca Zidane": "齐达内(卢卡)",
  "Meme": "梅梅",
  "Roberto Martinez": "罗伯托·马丁内斯",
  "Sebastien Desabre": "德萨布尔",
  "Lionel Scaloni": "斯卡洛尼",
  "Ralf Rangnick": "朗尼克",
  "Stale Solbakken": "索尔巴肯",
  "Graham Arnold": "阿诺德",
  "Jamal Sellami": "塞拉米",
  "Vladimir Petkovic": "佩特科维奇",
  "Szymon Marciniak": "马尔钦尼亚克",
  "Dahane Beida": "贝达",
  "Pierre Ghislain Atcho": "阿乔",
  // —— 2026-06-18 全队 squad 补译：48 队 /players/squads 全名单（API-Football）——
  "Carlos Acevedo López": "阿塞韦多",
  "Francisco Ochoa Magaña": "奥乔亚",
  "J. Rangel": "兰赫尔",
  "José Rangel Aguilar": "兰赫尔",
  "Jesús Gallardo Vasconcelos": "加亚尔多",
  "César Montes Castro": "蒙特斯",
  "Israel Reyes Romero": "雷耶斯",
  "J. Sánchez": "桑切斯",
  "Jorge Sánchez Ramos": "桑切斯",
  "J. Vásquez": "巴斯克斯",
  "Johan Vázquez Ibarra": "巴斯克斯",
  "E. Álvarez": "埃德森·阿尔瓦雷斯",
  "Edson Álvarez Velázquez": "埃德森·阿尔瓦雷斯",
  "M. Chávez": "马特奥·查韦斯",
  "Mateo Chávez García": "马特奥·查韦斯",
  "Obed Gómez Vargas": "巴尔加斯",
  "L. Chávez": "路易斯·查韦斯",
  "Luis Chávez Magallón": "路易斯·查韦斯",
  "Álvaro Fidalgo Fernández": "菲达尔戈",
  "B. Gutiérrez": "古铁雷斯",
  "É. Lira": "利拉",
  "Érik Lira Méndez": "利拉",
  "Gilberto Mora Zambrano": "莫拉",
  "Orbelín Pineda Alvarado": "皮内达",
  "Luis Romo Barrón": "罗莫",
  "Roberto Alvarado Hernández": "阿尔瓦拉多",
  "S. Giménez": "希门尼斯",
  "A. González": "冈萨雷斯",
  "Armando González Alba": "冈萨雷斯",
  "C. Huerta": "韦尔塔",
  "César Huerta Valera": "韦尔塔",
  "R. Jiménez": "拉乌尔·希门尼斯",
  "Raúl Jiménez Rodríguez": "拉乌尔·希门尼斯",
  "G. Martínez": "马丁内斯",
  "Guillermo Martínez Ayala": "马丁内斯",
  "J. Quiñones": "基尼奥内斯",
  "Julián Quiñones Quiñones": "基尼奥内斯",
  "Ernesto Vega Rojas": "贝加",
  "D. Kotarski": "科塔尔斯基",
  "Dominik Kotarski": "科塔尔斯基",
  "D. Livakovic": "利瓦科维奇",
  "I. Pandur": "潘杜尔",
  "Ivor Pandur": "潘杜尔",
  "D. Caleta-Car": "查莱塔-察尔",
  "M. Erlic": "埃尔利奇",
  "J. Gvardiol": "格瓦迪奥尔",
  "Joško Gvardiol": "格瓦迪奥尔",
  "Ezri Konsa": "孔萨",
  "Nico O'Reilly": "奥赖利",
  "Elliot Anderson": "安德森",
  "Noni Madueke": "马杜埃凯",
  "Djed Spence": "斯彭斯",
  "Jarell Quansah": "昆萨",
  "Marc Guéhi": "格伊",
  "Ollie Watkins": "沃特金斯",
  "M. Pongracic": "蓬格拉契奇",
  "J. Stanisic": "斯塔尼希奇",
  "J. Sutalo": "苏塔洛",
  "L. Vuskovic": "武什科维奇",
  "M. Baturina": "巴图里纳",
  "Martin Baturina": "巴图里纳",
  "T. Fruk": "弗鲁克",
  "Toni Fruk": "弗鲁克",
  "K. Jakic": "雅基奇",
  "M. Kovacic": "科瓦契奇",
  "L. Modric": "莫德里奇",
  "N. Moro": "莫罗",
  "Nikola Moro": "莫罗",
  "Mario Pasalic": "马里奥·帕萨利奇",
  "L. Sucic": "卢卡·苏契奇",
  "P. Sucic": "佩塔尔·苏契奇",
  "N. Vlasic": "弗拉希奇",
  "A. Budimir": "布迪米尔",
  "Ante Budimir": "布迪米尔",
  "A. Kramaric": "克拉马里奇",
  "I. Matanovic": "马塔诺维奇",
  "P. Musa": "穆萨",
  "Petar Musa": "穆萨",
  "Marco Pasalic": "马尔科·帕萨利奇",
  "I. Perisic": "佩里西奇",
  "Dominik Livaković": "利瓦科维奇",
  "Josip Šutalo": "苏塔洛",
  "Luka Vušković": "武什科维奇",
  "Josip Stanišić": "斯塔尼希奇",
  "Luka Modrić": "莫德里奇",
  "Petar Sučić": "佩塔尔·苏契奇",
  "Ivan Perišić": "佩里西奇",
  "Mario Pašalić": "马里奥·帕萨利奇",
  "Duje Ćaleta-Car": "查莱塔-察尔",
  "Marin Pongračić": "蓬格拉契奇",
  "Martin Erlić": "埃尔利奇",
  "Mateo Kovačić": "科瓦契奇",
  "Kristijan Jakić": "雅基奇",
  "Luka Sučić": "卢卡·苏契奇",
  "Marco Pašalić": "马尔科·帕萨利奇",
  "Nikola Vlašić": "弗拉希奇",
  "Andrej Kramarić": "克拉马里奇",
  "Igor Matanović": "马塔诺维奇",
  "A. Beiranvand": "贝兰万德",
  "Alireza Safar Beiranvand": "贝兰万德",
  "H. Hosseini": "侯赛尼",
  "Seyed Hosseini": "侯赛尼",
  "P. Niazmand": "尼亚兹曼德",
  "Seyed Niazmand Ghader": "尼亚兹曼德",
  "D. Eiri": "埃里",
  "Ramin Rezaeian Semeskandi": "雷扎伊安",
  "E. Hajisafi": "哈吉萨菲",
  "Ehsan Hajisafi": "哈吉萨菲",
  "H. Kanani": "卡纳尼",
  "Mohammad Kanani Zadegan": "卡纳尼",
  "S. Khalilzadeh": "哈利勒扎德",
  "M. Mohammadi": "穆罕默迪",
  "Milad Mohammadi Keshmarzi": "穆罕默迪",
  "A. Nemati": "内马提",
  "A. Jahanbakhsh": "贾汗巴赫什",
  "Alireza Jahanbakhsh Jirandeh": "贾汗巴赫什",
  "R. Cheshmi": "切什米",
  "S. Ezatolahi": "埃扎托拉希",
  "Saeed Ezatolahi Afagh": "埃扎托拉希",
  "Sayed Ghoddos": "戈多斯",
  "A. Razzaghinia": "拉扎吉尼亚",
  "Amir Razzaghinia": "拉扎吉尼亚",
  "M. Ghorbani": "戈尔巴尼",
  "M. Torabi": "托拉比",
  "Mehdi Ghaedi": "加埃迪",
  "Ali Alipourghara": "阿里普尔",
  "Shahriyar Moghanlou": "莫甘卢",
  "D. Eckert Ayensa": "埃克特·阿延萨",
  "Dennis-Yerai Eckert Ayensa": "埃克特·阿延萨",
  "M. Maignan": "迈尼昂",
  "R. Risser": "里塞尔",
  "Robin Risser Birckel": "里塞尔",
  "B. Samba": "桑巴",
  "L. Hernández": "卢卡斯·埃尔南德斯",
  "T. Hernández": "特奥·埃尔南德斯",
  "Théo Hernández": "特奥·埃尔南德斯",
  "I. Konaté": "科纳特",
  "J. Koundé": "孔德",
  "M. Lacroix": "拉克鲁瓦",
  "Dayotchanculle Upamecano": "于帕梅卡诺",
  "Mathis Cherki": "谢尔基",
  "N. Kanté": "坎特",
  "M. Koné": "穆罕默德·科内",
  "Adrien Rabiot-Provost": "拉比奥",
  "A. Tchouaméni": "琼阿梅尼",
  "W. Zaïre-Emery": "扎伊尔-埃梅里",
  "O. Dembélé": "登贝莱",
  "Masour Dembélé": "登贝莱",
  "D. Doué": "杜埃",
  "Kylian Mbappé Lottin": "姆巴佩",
  "Marcus Thuram-Ulien": "图拉姆",
  "Grant Campbell Hanley": "汉利",
  "Aaron Buchanan Hickey": "希基",
  "Scott Fraser McKenna": "麦肯纳",
  "Anthony Ralston": "拉尔斯顿",
  "Andrew Robertson": "罗伯逊",
  "J.  McGinn": "麦金",
  "Kenneth McLean": "麦克莱恩",
  "Ché Adams": "亚当斯",
  "B. Doak": "多克",
  "Ben Gannon Doak": "多克",
  "Hiroki Ito": "伊藤洋辉",
  "Kodai Sano": "佐野航大",
  "Alisson Becker": "阿利松",
  "Ederson Santana de Moraes": "埃德松",
  "Weverton Pereira da Silva": "韦弗顿",
  "Alex Lobo Silva": "阿莱士·桑德罗",
  "Gleison Silva Nascimento": "布雷默",
  "Gabriel dos Santos Magalhães": "加布里埃尔",
  "Ibañez": "伊巴涅斯",
  "Roger Ibañez da Silva": "伊巴涅斯",
  "Leonardo Pereira": "莱奥·佩雷拉",
  "Marcos Aoás Corrêa": "马尔基尼奥斯",
  "Douglas dos Santos Justino de Melo": "道格拉斯·桑托斯",
  "Éderson Silva": "埃德松·席尔瓦",
  "Danilo da Silva": "达尼洛",
  "Bruno Guimarães Rodriguez Moura": "布鲁诺·吉马良斯",
  "Carlos Casimiro": "卡塞米罗",
  "Fábio Tavares": "法比尼奥",
  "Lucas Tolentino Coelho de Lima": "帕奎塔",
  "Danilo dos Santos de Oliveira": "达尼洛·桑托斯",
  "Matheus Carneiro da Cunha": "马特乌斯·库尼亚",
  "Endrick Moreira de Sousa": "恩德里克",
  "Luiz Rosa da Silva": "路易斯·恩里克",
  "Gabriel Martinelli Silva": "马丁内利",
  "Neymar": "内马尔",
  "Neymar da Silva Santos Júnior": "内马尔",
  "Raphael Dias Belloli": "拉菲尼亚",
  "Rayan Simplício Rocha": "拉扬",
  "Thiago": "蒂亚戈",
  "Igor Nascimento Rodrigues": "蒂亚戈",
  "Vinícius Paixão de Oliveira Júnior": "维尼修斯",
  "B. Ergashev": "埃尔加舍夫",
  "Botirali Ergashev": "埃尔加舍夫",
  "A. Nematov": "内马托夫",
  "U. Yusupov": "尤苏波夫",
  "Utkir Yusupov": "尤苏波夫",
  "K. Alijonov": "阿利约诺夫",
  "Khojiakbar Alijonov": "阿利约诺夫",
  "R. Ashurmatov": "阿舒尔马托夫",
  "Rustamjon Ashurmatov": "阿舒尔马托夫",
  "U. Eshmurodov": "埃什穆罗多夫",
  "Umar Eshmurodov": "埃什穆罗多夫",
  "B. Karimov": "卡里莫夫",
  "Behruzjon Karimov": "卡里莫夫",
  "A. Khusanov": "胡萨诺夫",
  "Abduqodir Khusanov": "胡萨诺夫",
  "S. Nasrullayev": "纳斯鲁拉耶夫",
  "Sherzod Nasrullayev": "纳斯鲁拉耶夫",
  "F. Sayfiev": "赛菲耶夫",
  "J. Urozov": "乌罗佐夫",
  "Jakhongir Urozov": "乌罗佐夫",
  "A. Abdullaev": "阿卜杜拉耶夫",
  "A. Ulmasaliev": "乌尔马萨利耶夫",
  "Avazbek Ulmasaliev": "乌尔马萨利耶夫",
  "J. Masharipov": "马沙里波夫",
  "Jaloliddin Masharipov": "马沙里波夫",
  "A. Ganiyev": "加尼耶夫",
  "J. Iskanderov": "伊斯坎德罗夫",
  "Jamshid Iskanderov": "伊斯坎德罗夫",
  "O. Hamrobekov": "哈姆罗别科夫",
  "Odiljon Hamrobekov": "哈姆罗别科夫",
  "A. Mozgovoy": "莫兹戈沃伊",
  "Akmal Mozgovoy": "莫兹戈沃伊",
  "O. Shukurov": "舒库罗夫",
  "Otabek Shukurov": "舒库罗夫",
  "A. Fayzullaev": "法伊祖拉耶夫",
  "Abbosbek Fayzullaev": "法伊祖拉耶夫",
  "S. Esanov": "埃萨诺夫",
  "Sherzod Esanov": "埃萨诺夫",
  "O. Orunov": "奥鲁诺夫",
  "D. Khamdamov": "哈姆达莫夫",
  "Dostonbek Khamdamov": "哈姆达莫夫",
  "A. Amonov": "阿莫诺夫",
  "Azizbek Amonov": "阿莫诺夫",
  "I. Sergeev": "谢尔盖耶夫",
  "Igor Sergeev": "谢尔盖耶夫",
  "E. Shomurodov": "绍穆罗多夫",
  "Eldor Azamat Shomurodov": "绍穆罗多夫",
  "Nawaf Al Aqidi": "阿基迪",
  "Ahmed Al Kassar": "卡萨尔",
  "Mohammed Al Owais": "奥韦斯",
  "Mohammed Abu Al Shamat": "沙马特",
  "Nawaf Abdulrahman Boushal": "布沙勒",
  "Abdulelah Al Amri": "阿姆里",
  "Moteb Al Harbi": "哈尔比",
  "Hassan Mahboob": "卡迪什",
  "Ali Hassan Muhammad Majrashi": "马杰拉希",
  "Hassan Tambakti": "坦巴克提",
  "Hassan Al Tambakti": "坦巴克提",
  "J. Thakri": "塔克里",
  "Nasser Al Dawsari": "纳赛尔·道萨里",
  "Ziyad Al Johani": "乔哈尼",
  "Ziyad Al Marwani Al Johani": "乔哈尼",
  "Abdullah Al Khaibari": "海巴里",
  "Ala Al Haji": "哈吉",
  "Khalid Al Ghannam": "甘纳姆",
  "Ayman Ahmed": "叶海亚",
  "Feras Al Brikan": "布里坎",
  "Abdullah Al Hamdan": "哈姆丹",
  "Saleh Al Shehri": "谢赫里",
  "Salem Al Dawsari": "多萨里",
  "P. Pentz": "彭茨",
  "Patrick Pentz": "彭茨",
  "A. Schlager": "施拉格",
  "F. Wiegele": "维格勒",
  "Florian Wiegele": "维格勒",
  "D. Affengruber": "阿芬格鲁伯",
  "David Affengruber": "阿芬格鲁伯",
  "David Olatukunbo Alaba": "阿拉巴",
  "Kevin Danso": "丹索",
  "M. Friedl": "弗里德尔",
  "Marco Friedl": "弗里德尔",
  "P. Lienhart": "利恩哈特",
  "S. Posch": "波施",
  "M. Svoboda": "斯沃博达",
  "Michael Svoboda": "斯沃博达",
  "D. Ljubičić": "柳比契奇",
  "Dejan Ljubičić": "柳比契奇",
  "F. Grillitsch": "格里利奇",
  "Florian Grillitsch": "格里利奇",
  "K. Laimer": "莱默尔",
  "A. Prass": "普拉斯",
  "Alexander Prass": "普拉斯",
  "A. Schöpf": "舍普夫",
  "Alessandro Schöpf": "舍普夫",
  "N. Seiwald": "赛瓦尔德",
  "Patrick Wimmer": "维默尔",
  "M. Gregoritsch": "格雷戈里奇",
  "Michael Gregoritsch": "格雷戈里奇",
  "L. Hornícek": "霍尔尼切克",
  "M. Kovár": "科瓦日",
  "R. Hranác": "赫拉纳奇",
  "D. Jurásek": "尤拉塞克",
  "L. Krejcí": "克雷伊奇",
  "J. Zelený": "泽莱尼",
  "M. Sadílek": "萨迪莱克",
  "T. Chorý": "霍里",
  "D. Visinský": "维辛斯基",
  "Aziz Eraltay Behich": "贝希奇",
  "Kai Clifton Trewin": "特雷温",
  "A. O Neill": "奥尼尔",
  "M. Touré": "图雷",
  "S. Mele": "梅莱",
  "Santiago Mele Castanero": "梅莱",
  "F. Muslera": "穆斯莱拉",
  "Néstor Muslera Micol": "穆斯莱拉",
  "S. Rochet": "罗切特",
  "Sergio Rochet Álvarez": "罗切特",
  "R. Araújo": "阿劳霍",
  "Ronald Araújo da Silva": "阿劳霍",
  "S. Bueno": "布埃诺",
  "Santiago Bueno Sciutto": "布埃诺",
  "S. Cáceres": "卡塞雷斯",
  "Sebastián Cáceres Ramos": "卡塞雷斯",
  "J. Giménez": "希门尼斯",
  "José Giménez de Vargas": "希门尼斯",
  "M. Olivera": "奥利韦拉",
  "Mathías Olivera Miramontes": "奥利韦拉",
  "G. Varela": "巴雷拉",
  "Guillermo Varela Olivera": "巴雷拉",
  "M. Viña": "比尼亚",
  "Matías Viña Susperreguy": "比尼亚",
  "R. Bentancur": "本坦库尔",
  "Rodrigo Bentancur Colmán": "本坦库尔",
  "E. Martínez": "马丁内斯",
  "Emiliano Martínez Toranza": "马丁内斯",
  "J. Sanabria": "萨纳布里亚",
  "Juan Sanabria Magole": "萨纳布里亚",
  "M. Ugarte": "乌加特",
  "Manuel Ugarte Ribeiro": "乌加特",
  "F. Valverde": "巴尔韦德",
  "Federico Valverde Dipetta": "巴尔韦德",
  "R. Zalazar": "萨拉萨尔",
  "Rodrigo Zalazar Martínez": "萨拉萨尔",
  "G. de Arrascaeta": "德阿拉斯卡埃塔",
  "Giorgian de Arrascaeta Benedetti": "德阿拉斯卡埃塔",
  "N. de la Cruz": "德拉克鲁斯",
  "Diego de la Cruz Arcosa": "德拉克鲁斯",
  "M. Araújo": "阿劳霍",
  "Maximiliano Araújo Vilches": "阿劳霍",
  "A. Canobbio": "卡诺比奥",
  "Agustín Canobbio Graviz": "卡诺比奥",
  "R. Aguirre": "阿吉雷",
  "Rodrigo Aguirre Soto": "阿吉雷",
  "J. Piquerez": "皮克雷斯",
  "Joaquín Piquerez Moreira": "皮克雷斯",
  "D. Núñez": "努涅斯",
  "Darwin Núñez Ribeiro": "努涅斯",
  "F. Pellistri": "佩利斯特里",
  "Facundo Pellistri Rebollo": "佩利斯特里",
  "B. Rodríguez": "罗德里格斯",
  "Paul Rodríguez Bravo": "罗德里格斯",
  "F. Viñas": "比尼亚斯",
  "Federico Viñas Barboza": "比尼亚斯",
  "M. Epolo": "埃波洛",
  "Matthieu Epolo": "埃波洛",
  "T. Fayulu": "法尤卢",
  "Timothy Fayulu": "法尤卢",
  "L. Mpasi": "姆帕西",
  "Lionel Mpasi-Nzau": "姆帕西",
  "D. Batubinsika": "巴图宾西卡",
  "Buduka Batubinsika": "巴图宾西卡",
  "G. Kalulu": "卡卢卢",
  "Gédéon Kalulu Kyatengwa": "卡卢卢",
  "S. Kapuadi": "卡普阿迪",
  "J. Kayembe": "卡延贝",
  "Joris Kayembe Ditu": "卡延贝",
  "A. Masuaku": "马苏阿库",
  "Fuka-Arthur Masuaku Kawela": "马苏阿库",
  "C. Mbemba": "姆本巴",
  "Chancel Mbemba Mangulu": "姆本巴",
  "A. Tuanzebe": "图安泽贝",
  "A. Wan-Bissaka": "万-比萨卡",
  "E. Kayembe": "卡延贝",
  "Edouard Kayembe Kayembe": "卡延贝",
  "S. Moutoussamy": "穆图萨米",
  "N. Mukau": "穆考",
  "C. Pickel": "皮克尔",
  "Charles Monginda Pickel": "皮克尔",
  "N. Sadiki": "萨迪基",
  "Noah Sadiki": "萨迪基",
  "A. Tshibola": "齐博拉",
  "Aaron Tshibola": "齐博拉",
  "N. Mbuku": "姆布库",
  "Nathanaël Mbuku": "姆布库",
  "T. Bongonda": "邦贡达",
  "Théo Bongonda Mbul'Ofeko Batomboat": "邦贡达",
  "C. Bakambu": "巴坎布",
  "S. Banza": "班扎",
  "Simon Banza": "班扎",
  "B. Cipenga": "西彭加",
  "Brian Kibambe Cipenga": "西彭加",
  "M. Elia": "埃利亚",
  "Meschack Elia Lina": "埃利亚",
  "G. Kakuta": "卡库塔",
  "Gaël Kakuta Mambenga": "卡库塔",
  "F. Mayele": "马耶莱",
  "Fiston Kalala Mayele": "马耶莱",
  "Y. Wissa": "维萨",
  "Ahmed Basil": "巴西勒",
  "Ahmed Fadhil Al Fadhli": "巴西勒",
  "Jalal Hassan Hachim": "哈希姆",
  "Jalal Hachim": "哈希姆",
  "Fahad Talib": "塔利布",
  "Fahad Raheem": "塔利布",
  "Merchas Ghazi Salih Doski": "多斯基",
  "Frans Putros": "普特罗斯",
  "Frans Jirjis Haddad": "普特罗斯",
  "Mustafa Saadoun": "萨敦",
  "Mustafa Saadoun Al Korji": "萨敦",
  "Rebin Solaka": "索拉卡",
  "Rebin Solaka Adhamat": "索拉卡",
  "Zayed Tahseen": "塔赫辛",
  "Ahmed Hasan Al Reeshawee": "里沙维",
  "Ahmed Al Reeshawee": "里沙维",
  "Munaf Younus": "尤努斯",
  "Munaf Al Tekreeti": "尤努斯",
  "Akam Rahman": "拉赫曼",
  "Amir Al Ammari": "阿马里",
  "Amir Aboud Al Ammari": "阿马里",
  "Youssef Amyn": "阿明",
  "Ibraheem Bayesh": "巴耶什",
  "Ibraheem Bayesh Kamil Al Kaabawi": "巴耶什",
  "A. Sher": "谢尔",
  "Aimar Sher": "谢尔",
  "Kevin Yakob": "雅各布",
  "Ali Al Hamadi": "哈马迪",
  "Marko Farji": "法尔吉",
  "Aymen Ghadhban": "侯赛因",
  "Ahmed Qasem": "卡西姆",
  "A. Y. Hashim": "哈希姆",
  "M. Crocombe": "克罗科姆",
  "Maxime Crocombe": "克罗科姆",
  "A. Paulsen": "保尔森",
  "Alexander Paulsen": "保尔森",
  "M. Woud": "伍德",
  "M. Boxall": "博克索尔",
  "F. de Vries": "德弗里斯",
  "Francis de Vries": "德弗里斯",
  "Callan Rennie Elliot": "埃利奥特",
  "Timothy Payne": "佩恩",
  "N. Pijnaker": "佩纳克",
  "Nando Zen Pijnaker": "佩纳克",
  "T. Smith": "史密斯",
  "Thomas Jefferson Smith": "史密斯",
  "F. Surman": "瑟曼",
  "L. Bayliss": "贝利斯",
  "J. Bell": "贝尔",
  "Joe Zen Robert Bell": "贝尔",
  "M. Garbett": "加贝特",
  "Matthew Garbett": "加贝特",
  "A. Rufer": "鲁弗",
  "K. Barbarouses": "巴尔巴鲁塞斯",
  "Konstantinos Barbarouses": "巴尔巴鲁塞斯",
  "B. Waine": "韦恩",
  "Benjamin Waine": "韦恩",
  "Christopher Wood": "伍德",
  "Christopher Brady": "布雷迪",
  "Matthew Geary Freese": "弗里斯",
  "Matthew Turner": "特纳",
  "Timothy Ream": "里姆",
  "Christopher Richards": "理查兹",
  "Joseph Scally": "斯卡利",
  "Cristian Roldan": "罗尔丹",
  "Timothy Tarpeh Weah": "维阿",
  "Alejandro Zendejas Saavedra": "森德哈斯",
  "Stuart Goss": "戈斯",
  "Aubrey Maphosa Modiba": "莫迪巴",
  "Kulumani Ndamane": "恩达马内",
  "Tholo Matuludi": "马图卢迪",
  "S. Sithole": "西托莱",
  "Sekotori Makgopa": "马克戈帕",
  "Á. Montero": "蒙特罗",
  "Álvaro Montero Perales": "蒙特罗",
  "D. Ospina": "奥斯皮纳",
  "David Ospina Ramírez": "奥斯皮纳",
  "C. Vargas": "巴尔加斯",
  "Camilo Vargas Gil": "巴尔加斯",
  "S. Arias": "阿里亚斯",
  "Santiago Arias Naranjo": "阿里亚斯",
  "W. Ditta": "迪塔",
  "Willer Ditta Pérez": "迪塔",
  "J. Lucumí": "卢库米",
  "Jhon Lucumí Bonilla": "卢库米",
  "D. Machado": "马查多",
  "Deiver Machado Mena": "马查多",
  "Y. Mina": "米纳",
  "Yerry Mina González": "米纳",
  "J. Mojica": "莫希卡",
  "Johan Mojica Palacio": "莫希卡",
  "D. Muñoz": "穆尼奥斯",
  "Daniel Muñoz Mejía": "穆尼奥斯",
  "G. Puerta": "普埃尔塔",
  "Gustavo Puerta Molano": "普埃尔塔",
  "D. Sánchez": "桑切斯",
  "Davinson Sánchez Mina": "桑切斯",
  "K. Castaño": "卡斯塔尼奥",
  "Kevin Castaño Gil": "卡斯塔尼奥",
  "J. Lerma": "莱尔马",
  "Jefferson Lerma Solís": "莱尔马",
  "J. Portilla": "波尔蒂利亚",
  "Juan Portilla Orozco": "波尔蒂利亚",
  "J. Arias": "哈法尔·阿里亚斯",
  "Jafar Miguel Arias": "哈法尔·阿里亚斯",
  "J. Carrascal": "卡拉斯卡尔",
  "Jorge Carrascal Guardo": "卡拉斯卡尔",
  "J. Quintero": "金特罗",
  "Juan Quintero Paniagua": "金特罗",
  "R. Rios": "里奥斯",
  "Richard Ríos Montoya": "里奥斯",
  "J. Rodríguez": "罗德里格斯",
  "José Rodríguez Francis": "罗德里格斯",
  "J. Campaz": "坎帕斯",
  "Jaminton Campaz": "坎帕斯",
  "J. Córdoba": "科尔多瓦",
  "José Córdoba Chambers": "科尔多瓦",
  "C. Hernández": "埃尔南德斯",
  "Juan Hernández Suárez": "埃尔南德斯",
  "L. Díaz": "路易斯·迪亚斯",
  "Luis Díaz Marulanda": "路易斯·迪亚斯",
  "A. Gómez": "戈麦斯",
  "Carlos Gómez Hinestroza": "戈麦斯",
  "L. Suárez": "苏亚雷斯",
  "Luis Suárez Charris": "苏亚雷斯",
  "B. Asare": "阿萨雷",
  "Benjamin Asare": "阿萨雷",
  "J. Anang": "阿南",
  "Joseph Tetteh Anang": "阿南",
  "L. Zigi": "齐吉",
  "Lawrence Zigi": "齐吉",
  "J. Adjetey": "阿杰泰",
  "Jonas Adjei Adjetey": "阿杰泰",
  "D. Luckassen": "卢卡森",
  "Derrick Luckassen": "卢卡森",
  "G. Mensah": "门萨",
  "Gideon Mensah": "门萨",
  "A. Seidu": "塞义杜",
  "Alidu Seidu": "塞义杜",
  "J. Opoku": "奥波库",
  "Joseph Osei Opoku": "奥波库",
  "K. Peprah Oppong": "奥蓬",
  "Kojo Peprah Oppong": "奥蓬",
  "A. Mumin": "穆明",
  "Khalid Mumin Suleman": "穆明",
  "M. Senaya": "塞纳亚",
  "Marvin Senaya": "塞纳亚",
  "A. Baba": "巴巴",
  "Abdul Baba": "巴巴",
  "E. Owusu": "奥乌苏",
  "Elisha Owusu": "奥乌苏",
  "T. Partey": "帕尔特伊",
  "Thomas Teye Partey": "帕尔特伊",
  "K. Sibo": "西博",
  "Kwasi Sibo": "西博",
  "Caleb Marfo Yirenkyi": "伊伦基",
  "Caleb Yirenkyi": "伊伦基",
  "A. Semenyo": "塞门约",
  "Antoine Semenyo": "塞门约",
  "A. Boakye": "博阿基耶",
  "Augustine Boakye": "博阿基耶",
  "A. Fatawu": "法塔乌",
  "Issahaku Fatawu": "法塔乌",
  "P. Adu": "阿杜",
  "Prince Adu": "阿杜",
  "B. Thomas-Asante": "托马斯-阿桑特",
  "Solomon Thomas-Asante": "托马斯-阿桑特",
  "J. Ayew": "乔丹·阿尤",
  "Jordan Ayew": "乔丹·阿尤",
  "C. Bonsu Baah": "邦苏·巴阿",
  "Christopher Bonsu Baah": "邦苏·巴阿",
  "I. Williams": "伊纳基·威廉斯",
  "Iñaki Dannis Williams": "伊纳基·威廉斯",
  "E. Nuamah": "努阿马",
  "Ernest Nuamah Appiah": "努阿马",
  "K. Sulemana": "苏莱曼纳",
  "Kamaldeen Sulemana": "苏莱曼纳",
  "Yazid Abu Layla": "亚齐德·阿布·莱拉",
  "Abdallah Al Fakhouri": "法胡里",
  "Noureddin Zaid": "努尔丁·扎伊德",
  "H. Abu Al Dahab": "阿布·达哈卜",
  "M. Abu Hasheesh": "阿布·哈希什",
  "Mohammad Abualnadi": "阿布纳迪",
  "Yazan Al Arab": "亚赞·阿拉伯",
  "Saed Al Rosan": "罗桑",
  "A. Badawi": "巴达维",
  "Abdallah Naseeb": "纳西卜",
  "Abdallah Musallam Naseeb": "纳西卜",
  "Saleem Obaid": "奥贝德",
  "Ibrahim Sa'deh": "萨阿德",
  "Nizar Al Rashdan": "拉什丹",
  "Noor Al Rawabdeh": "拉瓦卜代",
  "Rajaei Ayed": "拉贾伊·阿耶德",
  "Rajaei Fadel Hasan": "拉贾伊·阿耶德",
  "Amer Jamous": "贾穆斯",
  "Mahmoud Al Mardi": "马尔迪",
  "Mohammed Abu Zurayq": "阿布·祖拉伊克",
  "Ali Ali Olwan": "奥尔万",
  "M. Abu Ghoush": "阿布·古什",
  "Mohammad Abu Ghoush": "阿布·古什",
  "Mousa Sulaiman Al Tamari": "塔马里",
  "M. Diaw": "迪奥",
  "Y. Diouf": "耶万·迪乌夫",
  "É. Mendy": "门迪",
  "Édouard Mendy": "门迪",
  "El Diouf": "埃尔·迪乌夫",
  "M. Niakhaté": "尼亚卡特",
  "M. Sarr": "马马杜·萨尔",
  "Pathé Ciss": "西斯",
  "Mouhamadou Diarra": "迪亚拉",
  "Idrissa Gueye": "盖伊",
  "Bara Ndiaye": "巴拉·恩迪亚耶",
  "Pape Sarr": "帕普·萨尔",
  "Assane Diao Diaoune": "迪亚奥",
  "Cheikh Mbacké Dieng": "迪昂",
  "S. Mané": "马内",
  "Pape Ndiaye": "帕普·恩迪亚耶",
  "Iliman Baroy Ndiaye": "伊利曼·恩迪亚耶",
  "Ricardo Ade": "阿德",
  "M. Expérience": "埃克斯佩里安斯",
  "Markhus Lacroix": "拉克鲁瓦",
  "D. Jean-Jacques": "让-雅克",
  "Danley Jean-Jacques": "让-雅克",
  "G. Métusala": "梅图萨拉",
  "Garven-Michée Métusala": "梅图萨拉",
  "Olivier Pierre": "皮埃尔",
  "C. F. Sainte": "圣特",
  "Louicius Deedson": "迪德森",
  "Derrick Etienne Jr.": "艾蒂安",
  "Y. Fortuné": "福尔蒂内",
  "Yassin Fortuné": "福尔蒂内",
  "Trevor Doornbusch": "多伦布施",
  "Sherel Floranus": "弗洛拉努斯",
  "Juriën Gaari": "加里",
  "Ar'jany Martha": "马尔塔",
  "K. Gorré": "戈雷",
  "H. Galíndez": "加林德斯",
  "M. Ramírez": "拉米雷斯",
  "Wellington Ramírez Preciado": "拉米雷斯",
  "Gonzalo Valle Bustamante": "巴列",
  "P. Estupiñán": "埃斯图皮尼安",
  "Pervis Estupiñán Tenorio": "埃斯图皮尼安",
  "P. Hincapié": "因卡皮耶",
  "Piero Hincapié Reyna": "因卡皮耶",
  "Yaimar Medina Ortiz": "梅迪纳",
  "J. Ordoñez": "奥多涅斯",
  "Joel Ordóñez Guerrero": "奥多涅斯",
  "Willian Pacho Tenorio": "帕乔",
  "Jackson Porozo Vernaza": "波罗索",
  "Angelo Preciado Quiñónez": "普雷西亚多",
  "Félix Torres Caicedo": "托雷斯",
  "J. Alcívar": "阿尔西瓦尔",
  "Jordy Alcívar Macías": "阿尔西瓦尔",
  "Moisés Caicedo Corozo": "凯塞多",
  "Denil Castillo Preciado": "卡斯蒂略",
  "Alan Franco Palma": "弗兰科",
  "K. Páez": "帕埃斯",
  "Ray Páez Andrade": "帕埃斯",
  "Alan Minda García": "明达",
  "Anthony Valencia Bajaña": "瓦伦西亚",
  "Pedro Vite Uca": "维特",
  "K. Rodríguez": "罗德里格斯",
  "Kevin Rodríguez Cortez": "罗德里格斯",
  "John Yeboah Zamora": "耶博阿",
  "Nilson Angulo Ramírez": "安古洛",
  "Jordy Caicedo Medina": "约迪·凯塞多",
  "Jeremy Arévalo": "阿雷瓦洛",
  "Jeremy Arévalo Mera": "阿雷瓦洛",
  "Gonzalo Plata Jiménez": "普拉塔",
  "Enner Valencia Lastra": "恩内尔·瓦伦西亚",
  "L. Mejía": "梅希亚",
  "Luis Mejía Cajar": "梅希亚",
  "O. Mosquera": "莫斯克拉",
  "Orlando Mosquera": "莫斯克拉",
  "C. Samudio": "萨穆迪奥",
  "César Samudio Murillo": "萨穆迪奥",
  "A. Andrade": "安德拉德",
  "Andrés Andrade Cedeño": "安德拉德",
  "C. Blackman": "布莱克曼",
  "César Blackman Camarena": "布莱克曼",
  "É. Davis": "戴维斯",
  "Éric Davis Grajales": "戴维斯",
  "F. Escobar": "埃斯科瓦尔",
  "Fidel Escobar Mendieta": "埃斯科瓦尔",
  "E. Fariña": "法里尼亚",
  "Edgardo Fariña Wynter": "法里尼亚",
  "J. Gutiérrez": "古铁雷斯",
  "Jorge Gutiérrez Cornejo": "古铁雷斯",
  "C. Harvey": "哈维",
  "Carlos Harvey Cesneros": "哈维",
  "R. Miller": "米勒",
  "Roderick Miller Molina": "米勒",
  "A. Murillo": "穆里略",
  "Michael Murillo Bermúdez": "穆里略",
  "J. Ramos": "拉莫斯",
  "Jiovany Ramos Díaz": "拉莫斯",
  "A. Carrasquilla": "卡拉斯基利亚",
  "Adalberto Carrasquilla Alcázar": "卡拉斯基利亚",
  "A. Godoy": "戈多伊",
  "Aníbal Godoy Lemus": "戈多伊",
  "C. Martinez": "马丁内斯",
  "Y. Bárcenas": "巴尔塞纳斯",
  "Édgar Bárcenas Herrera": "巴尔塞纳斯",
  "I. Díaz": "迪亚斯",
  "Ismael Díaz de León": "迪亚斯",
  "A. Quintero": "金特罗",
  "Alberto Quintero Medina": "金特罗",
  "C. Yanis": "亚尼斯",
  "César Yanis Velasco": "亚尼斯",
  "J. Fajardo": "法哈多",
  "José Fajardo Nelson": "法哈多",
  "A. Londoño": "隆多尼奥",
  "Azarías Londoño González": "隆多尼奥",
  "T. Rodríguez": "托马斯·罗德里格斯",
  "Tomás Rodríguez Mena": "托马斯·罗德里格斯",
  "C. Waterman": "沃特曼",
  "Cecilio Waterman Ruíz": "沃特曼",
  "J. Musso": "穆索",
  "Juan Musso": "穆索",
  "G. Rulli": "鲁利",
  "Gerónimo Rulli": "鲁利",
  "F. Medina": "梅迪纳",
  "Nahuel Molina Lucero": "莫利纳",
  "N. Tagliafico": "塔利亚菲科",
  "Nicolás Tagliafico": "塔利亚菲科",
  "V. Barco": "巴尔科",
  "Valentín Barco": "巴尔科",
  "E. Fernández": "恩佐·费尔南德斯",
  "G. Lo Celso": "洛塞尔索",
  "Giovani Lo Celso": "洛塞尔索",
  "A. Mac Allister": "麦卡利斯特",
  "E. Palacios": "帕拉西奥斯",
  "Exequiel Palacios": "帕拉西奥斯",
  "L. Paredes": "帕雷德斯",
  "Leandro Paredes": "帕雷德斯",
  "N. González": "尼古拉斯·冈萨雷斯",
  "R. De Paul": "德保罗",
  "J. Álvarez": "胡利安·阿尔瓦雷斯",
  "Nicolás Paz Martínez": "尼科·帕斯",
  "J. López": "洛佩斯",
  "José López": "洛佩斯",
  "Lionel Messi Cuccittini": "梅西",
  "G. Simeone": "西蒙尼",
  "Giuliano Simeone Baldini": "西蒙尼",
  "M. Senesi": "塞内西",
  "Marcos Senesi Barón": "塞内西",
  "O. Benbot": "本博特",
  "Oussama Benbot": "本博特",
  "M. Mastil": "马斯蒂尔",
  "Melvin Mastil": "马斯蒂尔",
  "L. Zidane": "卢卡·齐达内",
  "Luca Zidane Fernández": "卢卡·齐达内",
  "A. Abada": "阿巴达",
  "Achref Abada": "阿巴达",
  "R. Aït-Nouri": "艾特-努里",
  "Z. Belaïd": "贝拉伊德",
  "Zinéddine Belaïd": "贝拉伊德",
  "R. Belghali": "贝尔加利",
  "R. Bensebaïni": "本塞拜尼",
  "Amir Bensebaïni": "本塞拜尼",
  "S. Chergui": "谢尔吉",
  "Samir Chergui": "谢尔吉",
  "J. Hadjam": "哈贾姆",
  "Jaouen Hadjam": "哈贾姆",
  "A. Mandi": "曼迪",
  "M. Tougai": "图盖",
  "Mohamed Tougai": "图盖",
  "Houssem-Eddine Chaâbane Aouar": "阿瓦尔",
  "Y. Titraoui": "蒂特拉维",
  "Yacine Titraoui": "蒂特拉维",
  "F. Chaïbi": "沙伊比",
  "Mohammed Amoura": "阿穆拉",
  "A. Benbouali": "本布阿利",
  "Ahmed Benbouali": "本布阿利",
  "Adil Boulbina": "布尔比纳",
  "F. Ghedjemis": "盖杰米斯",
  "Farès Ghedjemis": "盖杰米斯",
  "A. Hadj-Moussa": "哈吉-穆萨",
  "Anis Hadj-Moussa": "哈吉-穆萨",
  "Y. Bounou": "布努",
  "Yassine Bounou": "布努",
  "M. Mohamedi": "穆罕默迪",
  "Munir Mohamedi El Kajoui": "穆罕默迪",
  "Ahmed Tagnaouti": "塔格纳维提",
  "M. Saâdane": "萨达内",
  "Marwane Saâdane": "萨达内",
  "Achraf Hakimi Mouh": "阿什拉夫",
  "Chadi Riad Dnanou": "里亚德",
  "Ismael Saibari Ben El Basra": "赛巴里",
  "Brahim Abdelkader Díaz": "布拉伊姆·迪亚斯",
  "A. Sbaï": "斯巴伊",
  "Mohamed Sbaï": "斯巴伊",
  "Arjan Malic": "马利奇",
  "Kerim-Sam Alajbegovic": "阿拉伊贝戈维奇",
  "D. Henderson": "迪恩·亨德森",
  "Dean Henderson": "迪恩·亨德森",
  "J. Pickford": "皮克福德",
  "Jordan Pickford": "皮克福德",
  "J. Trafford": "特拉福德",
  "James Trafford": "特拉福德",
  "D. Burn": "伯恩",
  "Dan Burn": "伯恩",
  "Daniel Burn": "伯恩",
  "M. Guéhi": "古埃伊",
  "Addji Guéhi": "古埃伊",
  "R. James": "詹姆斯",
  "Reece James": "詹姆斯",
  "E. Konsa": "孔萨",
  "Ezri Konsa Ngoyo": "孔萨",
  "T. Livramento": "利夫拉门托",
  "Valentino Livramento": "利夫拉门托",
  "N. Oreilly": "奥莱利",
  "J. Quansah": "匡萨",
  "Jarell Amorin Quansah": "匡萨",
  "D. Spence": "斯彭斯",
  "Diop Djed-Hotep Spence": "斯彭斯",
  "J. Stones": "斯通斯",
  "John Stones": "斯通斯",
  "E. Anderson": "安德森",
  "Eduardo Anderson Gómez": "安德森",
  "J. Bellingham": "贝林厄姆",
  "Jude Bellingham": "贝林厄姆",
  "E. Eze": "埃泽",
  "Eberechi Eze": "埃泽",
  "J. Henderson": "乔丹·亨德森",
  "Jordan Henderson": "乔丹·亨德森",
  "K. Mainoo": "梅努",
  "Kobbie Mainoo": "梅努",
  "D. Rice": "赖斯",
  "Declan Rice": "赖斯",
  "M. Rogers": "罗杰斯",
  "Morgan Rogers": "罗杰斯",
  "A. Gordon": "戈登",
  "Anthony Gordon": "戈登",
  "H. Kane": "凯恩",
  "Harry Kane": "凯恩",
  "N. Madueke": "马杜埃凯",
  "Chukwunonso Madueke": "马杜埃凯",
  "M. Rashford": "拉什福德",
  "Marcus Rashford": "拉什福德",
  "B. Saka": "萨卡",
  "Bukayo Saka": "萨卡",
  "I. Toney": "托尼",
  "Ivan Toney": "托尼",
  "O. Watkins": "沃特金斯",
  "Oliver Watkins": "沃特金斯",
  "Orlando Gill Noldin": "吉尔",
  "Gastón Olveira Echeverría": "奥尔韦拉",
  "Omar Alderete Fernández": "阿尔德雷特",
  "Júnior Alonso Mujica": "阿隆索",
  "J. Cáceres": "卡塞雷斯",
  "F. Balbuena": "巴尔武埃纳",
  "Fabián Balbuena González": "巴尔武埃纳",
  "G. Gómez": "古斯塔沃·戈麦斯",
  "Gustavo Gómez Portillo": "古斯塔沃·戈麦斯",
  "Alexandro Maidana Mendieta": "迈达纳",
  "G. Velázquez": "贝拉斯克斯",
  "Víctor Velázquez Ramos": "贝拉斯克斯",
  "José Canale Domínguez": "卡纳莱",
  "Damián Bobadilla Benítez": "博瓦迪利亚",
  "Gustavo Caballero González": "卡瓦列罗",
  "Adrián Cubas": "库巴斯",
  "Matías Galarza Fonda": "加拉萨",
  "D. Gómez": "迭戈·戈麦斯",
  "Diego Gómez Amarilla": "迭戈·戈麦斯",
  "Maurício": "毛里西奥",
  "Maurício Magalhães Prado": "毛里西奥",
  "Braian Ojeda Rodríguez": "奥赫达",
  "Ramón Sosa Acosta": "索萨",
  "M. Almirón": "阿尔米隆",
  "Miguel Almirón Rejala": "阿尔米隆",
  "A. Romero": "罗梅罗",
  "Alejandro Romero Gamarra": "罗梅罗",
  "Alex Arce Barrios": "阿尔塞",
  "G. Ávalos": "阿瓦洛斯",
  "Gabriel Ávalos Stumpfs": "阿瓦洛斯",
  "Julio Enciso Espínola": "恩西索",
  "Isidro Pitta Saldívar": "皮塔",
  "Arnaldo Sanabria Ayala": "萨纳布里亚",
  "M. Alaa": "穆罕默德·阿拉",
  "Mohamed El Shenawy": "谢纳维",
  "Mohamed Gomaa": "谢纳维",
  "Mostafa Mohamed Shobeir": "舒贝尔",
  "Al Mahdi Soliman": "苏莱曼",
  "Al Soliman": "苏莱曼",
  "Hossam Abdelsalam Abdelmaguid": "阿卜杜勒马吉德",
  "Mohamed Mohamed Ahmed": "阿卜杜勒蒙内姆",
  "Karim Ramadan Seif El Din": "哈菲兹",
  "Mohamed Gamal Eldemerdash": "哈尼",
  "Yasser Ibrahim El Hanafi": "亚西尔·易卜拉欣",
  "T. Alaa": "塔列克·阿拉",
  "Emam Abdelghany": "阿舒尔",
  "Marwan Fahim Ghallab": "阿提亚",
  "Nabil Emad Dunga": "邓加",
  "Nabil Al El Mahdy": "邓加",
  "Hamdi Fathy": "法蒂",
  "Hamdi Abdul Fattah": "法蒂",
  "Mohanad Ahmed Abdelmonem": "拉辛",
  "Mahmoud Abdelmohsen Hassan": "萨贝尔",
  "Mostafa Zico": "齐科",
  "Mostafa Zaki Abdelraouf": "齐科",
  "Trézéguet": "特雷泽盖",
  "Mahmoud Hassan": "特雷泽盖",
  "H. Hassan": "哈伊塞姆·哈桑",
  "Ahmed Zizo": "齐祖",
  "H. Abdelkarim": "阿卜杜勒卡里姆",
  "Ibrahim Hassan": "易卜拉欣·阿德尔",
  "Mohamed Salah Hamed Mahrous Ghaly": "萨拉赫",
  "U. Çakir": "查克尔",
  "M. Günok": "居诺克",
  "Fehmi Günok": "居诺克",
  "Samet Akaydin": "阿卡伊登",
  "Z. Çelik": "切利克",
  "Mehmet Çelik": "切利克",
  "M. Müldür": "缪尔迪尔",
  "Ç. Söyüncü": "索云居",
  "H. Çalhanoglu": "恰尔汗奥卢",
  "O. Kokçu": "科克丘",
  "S. Özcan": "厄兹詹",
  "I. Yüksek": "尤克塞克",
  "A. Güler": "京勒",
  "Y. Akgün": "阿克京",
  "K. Aktürkoglu": "阿克蒂尔克奥卢",
  "D. Gül": "居尔",
  "S. Ben Hsan": "本·哈桑",
  "Sabri Ben Hsan": "本·哈桑",
  "C. Abdelmouhib": "阿卜杜勒穆希卜",
  "Ali El Abdi": "阿卜迪",
  "Adam Arous": "阿鲁斯",
  "A. Ben Hmida": "本·哈米达",
  "Mohamed Ben Hmida": "本·哈米达",
  "Moutaz Neffati": "内法蒂",
  "Ahmed Ben Ouanes": "本·瓦内斯",
  "Ismaël Gharbi": "加尔比",
  "A. Ben Slimane": "本·斯利曼",
  "H. Mahmoud": "马哈茂德",
  "Mohamed Achouri": "阿舒里",
  "N. Aké": "阿克",
  "J. van Hecke": "范赫克",
  "Jan van Hecke": "范赫克",
  "M. de Roon": "德龙",
  "Brian Adjei Brobbey": "布罗比",
  "Diogo Meireles da Costa": "迪奥戈·科斯塔",
  "José Sá": "若泽·萨",
  "José Malheiro de Sá": "若泽·萨",
  "Rui Silva": "鲁伊·席尔瓦",
  "Rui Dantas da Silva": "鲁伊·席尔瓦",
  "Tomás Lemos Araújo": "阿劳若",
  "João Cavaco Cancelo": "坎塞洛",
  "Diogo Dalot": "达洛特",
  "José Dalot Teixeira": "达洛特",
  "Rúben Dias": "鲁本·迪亚斯",
  "Rúben dos Santos Gato Alves Dias": "鲁本·迪亚斯",
  "Gonçalo Inácio": "伊纳西奥",
  "Nuno Tavares Mendes": "努诺·门德斯",
  "Nélson Semedo": "塞梅多",
  "Nélson Cabral Semedo": "塞梅多",
  "Renato da Palma Veiga": "维加",
  "Samú Costa": "萨穆·科斯塔",
  "Samuel de Almeida Costa": "萨穆·科斯塔",
  "Bruno Borges Fernandes": "B费",
  "João Gonçalves Neves": "若昂·内维斯",
  "Rúben Neves": "鲁本·内维斯",
  "Rúben da Silva Neves": "鲁本·内维斯",
  "Matheus Nunes": "努内斯",
  "Bernardo Mota Veiga de Carvalho e Silva": "B席尔瓦",
  "Vítor Machado Ferreira": "维蒂尼亚",
  "Francisco Conceição": "孔塞桑",
  "Francisco Fernandes da Conceição": "孔塞桑",
  "Gonçalo Guedes": "格德斯",
  "Gonçalo Ganchinho Guedes": "格德斯",
  "João Félix": "菲利克斯",
  "João Félix Sequeira": "菲利克斯",
  "Rafael Leão": "莱昂",
  "Rafael da Conceição Leão": "莱昂",
  "Pedro Lomba Neto": "内托",
  "Gonçalo Ramos": "拉莫斯",
  "Gonçalo Matias Ramos": "拉莫斯",
  "Cristiano dos Santos Aveiro": "C罗",
  "Trincão": "特林康",
  "Francisco Machado Mota de Castro Trincão": "特林康",
  "Joan García Pons": "若安·加西亚",
  "David Raya Martin": "拉亚",
  "Unai Simón Mendibil": "乌奈·西蒙",
  "Pau Cubarsí Paredes": "库巴尔西",
  "Marc Cucurella Saseta": "库库雷利亚",
  "Eric García Martret": "埃里克·加西亚",
  "Álex Grimaldo": "格里马尔多",
  "Alejandro Grimaldo García": "格里马尔多",
  "Marcos Llorente Moreno": "略伦特",
  "Pedro Porro Sauceda": "波罗",
  "Marc Pubill Pagès": "普比尔",
  "Gavi": "加维",
  "Pablo Páez Gavira": "加维",
  "Mikel Merino Zazón": "梅里诺",
  "Pedro González López": "佩德里",
  "Rodrigo Hernández Cascante": "罗德里",
  "Fabián Ruiz Peña": "法比安·鲁伊斯",
  "Martín Zubimendi Ibáñez": "苏比门迪",
  "Álex Baena": "巴埃纳",
  "Alejandro Baena Rodríguez": "巴埃纳",
  "Daniel Olmo Carvajal": "奥尔莫",
  "Borja Iglesias Quintás": "伊格莱西亚斯",
  "Lamine Yamal Nasraoui Ebana": "亚马尔",
  "Víctor Muñoz Villanueva": "维克托·穆尼奥斯",
  "Mikel Oyarzabal Ugarte": "奥亚萨瓦尔",
  "Yeremy Pino": "皮诺",
  "Yeremy Pino Santos": "皮诺",
  "Ferran Torres García": "费兰·托雷斯",
  "Nicholas Williams Arthuer": "尼科·威廉姆斯",
  "Ø. Nyland": "尼兰",
  "Ørjan Håskjold Nyland": "尼兰",
  "E. Selvik": "塞尔维克",
  "Egil Selvik": "塞尔维克",
  "S. Tangvik": "唐格维克",
  "Sander Tangvik": "唐格维克",
  "K. Ajer": "阿耶尔",
  "Kristoffer Vassbakk Ajer": "阿耶尔",
  "F. Bjørkan": "比约尔坎",
  "Fredrik Bjørkan": "比约尔坎",
  "H. Falchener": "法尔切纳",
  "Henrik Sælebakke Falchener": "法尔切纳",
  "S. Langås": "朗格斯",
  "Sondre Klingen Langås": "朗格斯",
  "T. Heggem": "海格姆",
  "Torbjørn Lysaker Heggem": "海格姆",
  "L. Østigård": "厄斯蒂高",
  "Leo Skiri Østigård": "厄斯蒂高",
  "M. Pedersen": "佩德森",
  "Marcus Holmgren Pedersen": "佩德森",
  "D. Møller Wolfe": "默勒·沃尔夫",
  "T. Aasgaard": "奥斯戈",
  "Thelo Aasgaard": "奥斯戈",
  "S. Berge": "贝里",
  "Sander Bolin Berge": "贝里",
  "M. Ødegaard": "厄德高",
  "M. Thorsby": "托斯比",
  "Morten Thorsby": "托斯比",
  "Andreas Rædergård Schjelderup": "舍尔德鲁普",
  "J. Hauge": "豪格",
  "Jens Hauge": "豪格",
  "Erling Braut Haaland": "哈兰德",
  "J. Strand Larsen": "斯特兰·拉森",
  "Jørgen Strand Larsen": "斯特兰·拉森",
  "Antonio Eromonsele Nordby Nusa": "努萨",
  "A. Sørloth": "瑟尔洛特",
  "J. Ryerson": "里尔森",
  "Mahmud Ibrahim Abunada": "阿布纳达",
  "Salah Mousa Hassan": "萨拉赫·扎卡里亚",
  "Homam Ahmed": "胡曼·艾哈迈德",
  "Sultan Al Braik": "苏丹·布拉伊克",
  "Jassem Gaber": "贾西姆·贾比尔",
  "Jassem Abdulsallam": "贾西姆·贾比尔",
  "G. Laye": "拉耶",
  "Pedro Carvalho Deus Correia": "佩德罗·米格尔",
  "Assim Al Haj Madibo": "马迪博",
  "Ahmed Al Ganehi": "加内希",
  "Abdulaziz Hatem": "哈特姆",
  "Abdulaziz Mohammed Abdullah": "哈特姆",
  "Ahmed Abdoun": "艾哈迈德·法蒂",
  "Mohamed Al Manai": "马纳伊",
  "Ahmed Alaa": "艾哈迈德·阿拉",
  "Ahmed Abdelmotaal": "艾哈迈德·阿拉",
  "Almoez Abdulla": "阿莫埃兹·阿里",
  "Edmilson da Silva": "埃德米尔森",
  "Tahsin Jamshid": "贾姆希德",
  "M. Crépeau": "克雷波",
  "D. St. Clair": "圣克莱尔",
  "Luc Rollet De Fougerolles": "德富热罗勒",
  "Richmond Laryea": "拉里亚",
  "M. Choinière": "舒瓦尼耶",
  "S. Eustáquio": "尤斯塔基奥",
  "Stephen Antunes Eustáquio": "尤斯塔基奥",
  "I. Koné": "科内",
  "Ismaël Koné": "科内",
  "Promise Akinpelu": "戴维",
  "Tanitoluwa Oluwatimikhin Oluwaseyi": "奥卢瓦塞伊",
  "Yvon Mvogo Nganoma": "姆沃戈",
  "E. Cömert": "科默特",
  "R. Rodríguez": "罗德里格斯",
  "Ricardo Rodríguez Araya": "罗德里格斯",
  "Mohameth Sow": "索乌",
  "Denis Zakaria Lako Lado": "扎卡里亚",
  "Cedric Itten": "伊滕",
  "Rubén Vargas Martínez": "巴尔加斯",
  "Mohamed Amdouni": "阿姆杜尼",
  "T. Courtois": "库尔图瓦",
  "S. Lammens": "拉门斯",
  "M. Penders": "彭德斯",
  "T. Castagne": "卡斯塔涅",
  "M. De Cuyper": "德库珀",
  "K. De Winter": "德温特",
  "Z. Debast": "德巴斯特",
  "Zeno Debast": "德巴斯特",
  "B. Mechele": "梅赫莱",
  "T. Meunier": "默尼耶",
  "N. Ngoy": "恩戈伊",
  "J. Seys": "塞斯",
  "A. Theate": "特亚特",
  "K. De Bruyne": "德布劳内",
  "A. Onana": "奥纳纳",
  "Amadou Mvom Onana": "奥纳纳",
  "N. Raskin": "拉斯金",
  "A. Saelemaekers": "萨勒马克斯",
  "Y. Tielemans": "蒂勒曼斯",
  "D. Moreira": "莫雷拉",
  "H. Vanaken": "瓦纳肯",
  "A. Witsel": "维特塞尔",
  "Axel Lambert Witsel": "维特塞尔",
  "J. Doku": "多库",
  "M. Fernandez-Pardo": "费尔南德斯-帕尔多",
  "Matias Fernandez-Pardo": "费尔南德斯-帕尔多",
  "R. Lukaku": "卢卡库",
  "Romelu Lukaku Bolingoli": "卢卡库",
  "D. Lukebakio": "卢克巴基奥",
  "Dodi Lukebakio Ngandoli": "卢克巴基奥",
  "C. De Ketelaere": "德凯特拉雷",
  "L. Trossard": "特罗萨德",
  "Márcio Salomão Brazão da Rosa": "马西奥·罗萨",
  "Vózinha": "沃济尼亚",
  "Josimar Évora Dias": "沃济尼亚",
  "C. dos Santos": "多斯桑托斯",
  "Carlos Antunes dos Santos": "多斯桑托斯",
  "Edilson Monteiro Sanches Borges": "迪内·博尔赫斯",
  "Logan Evans Costa": "洛根·科斯塔",
  "S. Lopes Cabral": "洛佩斯·卡布拉尔",
  "Roberto Lopes": "皮科",
  "S. Moreira": "斯蒂芬·莫雷拉",
  "Wagner Cardoso Pina": "瓦格纳·皮纳",
  "Kelvin Spencer Pires": "凯尔文·皮雷斯",
  "Ianique dos Santos Tavares": "斯托皮拉",
  "Telmo Gomes Arcanjo": "特尔莫·阿尔坎茹",
  "L. Duarte": "杜阿尔特",
  "Laros d'Encarnação Duarte": "杜阿尔特",
  "João Moreira Fernandes": "若昂·保罗",
  "Kevin Pina": "凯文·皮纳",
  "Kevin Gonçalves Pereira de Pina": "凯文·皮纳",
  "Jamiro Monteiro Alvarenga": "蒙泰罗",
  "Jair Semedo Monteiro": "亚尼克·塞梅多",
  "Garry Mendes Rodrigues": "罗德里格斯",
  "Nuno da Costa": "努诺·达科斯塔",
  "Nuno da Costa Jóia": "努诺·达科斯塔",
  "Jovane Borges Cabral": "若瓦内·卡布拉尔",
  "Willy Semedo Afonso": "威利·塞梅多",
  "Hélio Oliveira Alves Varela": "瓦雷拉",
  "Ryan Mendes da Graça": "门德斯",
  "Gilson Benchimol": "本希莫尔",
  "Gilson Benchimol Tavares": "本希莫尔",
  "D. Livramento": "利夫拉门托",
  "Dailon Rocha Livramento do Rosario": "利夫拉门托",
  "Hyeon-Woo Jo": "赵贤祐",
  "Seung-Gyu Kim": "金承奎",
  "Bum-Keun Song": "宋范根",
  "Wi-Je Cho": "赵维制",
  "Min-Jae Kim": "金玟哉",
  "Moon-Hwan Kim": "金文奂",
  "Tae-Hyeon Kim": "金泰贤",
  "Park Jin-Seop": "朴镇燮",
  "Jin-Seop Park": "朴镇燮",
  "Tae-Seok Lee": "李泰锡",
  "Young-Woo Seol": "薛英佑",
  "Ji-Sung Eom": "严志成",
  "In-Beom Hwang": "黄仁范",
  "Jin-Gyu Kim": "金珍圭",
  "Dong-Gyeong Lee": "李同庆",
  "Jae-Sung Lee": "李在城",
  "Kang-In Lee": "李刚仁",
  "Seung-Ho Paik": "白升浩",
  "Hyun-Jun Yang": "梁玹准",
  "Hee-Chan Hwang": "黄喜灿",
  "Gue-Sung Cho": "赵圭成",
  "Hyeon-Gyu Oh": "吴贤揆",
  "Heung-Min Son": "孙兴慜",
  "Alban-Marc Lafont": "拉丰",
  "Emmanuel Djedje Agbadou Badobre": "阿巴杜",
  "G. Doué": "格埃拉·杜埃",
  "Kouakou Kossounou": "科苏努",
  "Obite Ndicka": "恩迪卡",
  "Christopher Téa Operi": "奥佩里",
  "F. Kessié": "凯西",
  "I. Sangaré": "桑加雷",
  "Jean Seri": "塞里",
  "B. Touré": "巴祖马纳·图雷",
  "O. Diakité": "迪亚基特",
  "Amad Diallo Traoré": "迪亚洛",
  "N. Pépé": "佩佩",
  "Sepe Wahi": "瓦希",
  "Bo Nordfeldt": "诺德费尔特",
  "J. Widell Zetterström": "维德尔·泽特斯特伦",
  "V. Lindelöf": "林德勒夫",
  "Victor Nilsson Lindelöf": "林德勒夫",
  "Yasin Abbas Ayari": "阿亚里",
  "Erik Nygren": "尼格伦",
  "J. Karlström": "卡尔斯特伦",
  "Kenneth Sema": "塞马",
  "Taha Ali": "塔哈·阿里",
  "Anthony Junior Elanga": "埃兰加",
  "Håkan Nilsson": "尼尔松",
  "A. Nübel": "纽贝尔",
  "Waldemar Riptsov Anton": "安东",
  "A. Rüdiger": "吕迪格",
  "Jonathan Glao Tah": "塔",
  "P. Groß": "格罗斯",
  "A. Ouédraogo": "瓦塔拉戈",
  "Forzan Ouédraogo": "瓦塔拉戈",
  "L. Sané": "萨内",
  "F. Conceicao": "弗朗西斯科·孔塞桑",
  "N. Semedo": "内尔松·塞梅多",
  "R. Leao": "拉斐尔·莱奥",

  // 加纳 vs 巴拿马官方阵容补译（API-Football 全名）
  "Lawrence Ati Zigi": "阿蒂·齐吉",
  "Joseph Anang": "约瑟夫·阿南",
  "Jerome Opoku": "奥波库",
  "Abdul Mumin": "阿卜杜勒·穆明",
  "Rahman Baba": "拉赫曼·巴巴",
  "Ernest Nuamah": "努阿马",
  "Abdul Fatawu Issahaku": "法塔乌",
  "Christopher Baah": "克里斯托弗·巴",
  "Iñaki Williams": "伊尼亚基·威廉姆斯",
  "Brandon Thomas-Asante": "托马斯-阿桑特",
  "Prince Kwabena Adu": "阿杜",
  "Carlos Queiroz": "卡洛斯·奎罗斯",
  "Luis Mejía": "路易斯·梅希亚",
  "César Samudio": "塞萨尔·萨穆迪奥",
  "Jiovany Ramos": "拉莫斯",
  "José Córdoba": "科尔多瓦",
  "Andrés Andrade": "安德拉德",
  "Amir Murillo": "阿米尔·穆里略",
  "Fidel Escobar": "菲德尔·埃斯科巴",
  "Edgardo Fariña": "法里尼亚",
  "Éric Davis": "埃里克·戴维斯",
  "Roderick Miller": "罗德里克·米勒",
  "Jorge Gutiérrez": "古铁雷斯",
  "Carlos Harvey": "哈维",
  "Yoel Bárcenas": "巴尔塞纳斯",
  "César Blackman": "布莱克曼",
  "Cristian Martínez": "马丁内斯",
  "Adalberto Carrasquilla": "卡拉斯基利亚",
  "Ismael Díaz": "伊斯梅尔·迪亚斯",
  "Alberto Quintero": "金特罗",
  "Aníbal Godoy": "戈多伊",
  "César Yanis": "亚尼斯",
  "Azarias Londoño": "隆多尼奥",
  "Tomás Rodríguez": "托马斯·罗德里格斯",
  "José Fajardo": "法哈多",
  "Cecilio Waterman": "沃特曼",
  "José Luis Rodríguez": "何塞·路易斯·罗德里格斯",
  "Thomas Christiansen": "托马斯·克里斯蒂安森",

  // —— 乌兹别克斯坦 ——
  "Utkir Yusupov": "尤苏波夫",
  "Abdukodir Khusanov": "库萨诺夫",
  "A. Khusanov": "库萨诺夫",
  "Rustam Ashurmatov": "阿舒尔马托夫",
  "Abdulla Abdullaev": "阿卜杜拉耶夫",
  "Bekhruz Karimov": "卡里莫夫",
  "Sherzod Nasrullaev": "纳斯鲁拉耶夫",
  "Oston Urunov": "乌鲁诺夫",
  "Eldor Shomurodov": "绍穆罗多夫",
  "E. Shomurodov": "绍穆罗多夫",
  "Abduvokhid Nematov": "内马托夫",
  "Khozhiakbar Alizhonov": "阿利忠诺夫",
  "Farrukh Sayfiev": "赛菲耶夫",
  "Umarbek Eshmuradov": "埃什穆拉多夫",
  "Avazbek Ulmasaliyev": "乌尔马萨利耶夫",
  "Jamshid Iskandarov": "伊斯坎达罗夫",
  "Odiljon Khamrobekov": "哈姆罗别科夫",
  "Ruslanbek Jiyanov": "吉亚诺夫",
  "Azizjon Ganiev": "加尼耶夫",
  "Azizbek Amanov": "阿马诺夫",
  "Fabio Cannavaro": "卡纳瓦罗",

  // —— 哥伦比亚 ——
  "Camilo Vargas": "卡米洛·巴尔加斯",
  "David Ospina": "奥斯皮纳",
  "Álvaro Montero": "蒙特罗",
  "Daniel Muñoz": "穆尼奥斯",
  "D. Muñoz": "穆尼奥斯",
  "Davinson Sánchez": "达文森·桑切斯",
  "Jhon Lucumí": "卢库米",
  "Yerry Mina": "耶里·米纳",
  "Willer Ditta": "迪塔",
  "Johan Mojica": "莫希卡",
  "Deiver Machado": "马查多",
  "Santiago Arias": "圣地亚哥·阿里亚斯",
  "Jefferson Lerma": "莱尔马",
  "J. Lerma": "莱尔马",
  "Gustavo Puerta": "普埃尔塔",
  "Kevin Castaño": "卡斯塔尼奥",
  "Richard Ríos": "里奥斯",
  "Juan Portilla": "波尔蒂利亚",
  "Jorge Carrascal": "卡拉斯卡尔",
  "Juan Fernando Quintero": "金特罗",
  "James Rodríguez": "哈梅斯·罗德里格斯",
  "J. Rodríguez": "哈梅斯·罗德里格斯",
  "Jhon Arias": "约翰·阿里亚斯",
  "J. Arias": "约翰·阿里亚斯",
  "Luis Díaz": "路易斯·迪亚斯",
  "L. Díaz": "路易斯·迪亚斯",
  "Luis Javier Suárez": "路易斯·苏亚雷斯",
  "L. Suárez": "路易斯·苏亚雷斯",
  "Jhon Córdoba": "科尔多瓦",
  "J. Córdoba": "科尔多瓦",
  "Cucho Hernández": "库乔·埃尔南德斯",
  "Andrés Gómez": "安德烈斯·戈麦斯",
  "Nestor Lorenzo": "内斯托尔·洛伦索",

  // —— 伊拉克 ——
  "Rebin Sulaka": "苏拉卡",
  "Ahmed Hasan Maknazi": "马克纳齐",
  "Mustafa Saadoon": "萨敦",
  "Mohanad Ali": "穆罕纳德·阿里",
  "Ali Yousif": "阿里·优素福",

  // —— 挪威 ——
  "Fredrik André Bjørkan": "比约尔坎",
  "Sondre Langås": "朗高斯",
  "Andreas Schjelderup": "谢尔德鲁普",
  "Marcus Pedersen": "佩德森",
  "Jens Petter Hauge": "豪格",

  // —— 阿根廷 ——
  "Marcos Senesi": "塞内西",
  "Giuliano Simeone": "朱利亚诺·西蒙尼",
  "Julián Alvarez": "胡利安·阿尔瓦雷斯",
  "J. Álvarez": "胡利安·阿尔瓦雷斯",
  "José Manuel López": "何塞·曼努埃尔·洛佩斯",

  // —— 阿尔及利亚 ——
  "Zineddine Belaid": "贝莱德",
  "Samir Sophian Chergui": "谢尔吉",
  "Houssem Aouar": "阿瓦尔",
  "Yassine Titraoui": "蒂特拉维",
  "Ahmed Nadhir Benbouali": "本布阿利",

  // —— 约旦 ——
  "Abdallah Al-Fakhouri": "法胡里",
  "Husam Ali Mohammad Abudahab": "阿布达哈布",
  "Saad Al Rousan": "鲁桑",
  "Anas Badawi": "巴达维",
  "Mohammad Ali Hasheesh": "哈希什",
  "Ibrahim Sadeh": "萨迪赫",
  "Mohammad Al Daoud": "达乌德",
  "Mohammad Abu Zrayq": "阿布·兹拉伊克",
  "Ali Al Azaizah": "阿扎伊扎",

  // —— 葡萄牙 ——
  "Francisco Trincão": "特林康",
  "F. Trincão": "特林康",

  // —— 刚果民主共和国 ——
  "Dylan Batubinsika": "巴图宾西卡",
  "Joris Kayembe": "卡延贝",
  "Gedeon Kalulu": "卡卢卢",
  "Théo Bongonda": "邦贡达",
  "Charles Pickel": "皮克尔",
  "Brian Cipenga": "西彭加",
  "Gaël Kakuta": "卡库塔",
  "Meschak Elia": "埃利亚",
  "Fiston Mayele": "马耶莱",

  // —— 教练 ——
  "Thomas Tuchel": "图赫尔",
  "Zlatko Dalic": "达利奇",

  // —— 事件缩写形式（去重音 ASCII，进球/助攻表用）——
  "L. Diaz": "路易斯·迪亚斯",
  "L. Suarez": "路易斯·苏亚雷斯",
  "J. Rodriguez": "哈梅斯·罗德里格斯",
  "D. Munoz": "穆尼奥斯",
  "C. Hernandez": "库乔·埃尔南德斯",
  "I. Diaz": "迪亚斯",
  "A. Londono": "隆多尼奥",
  "O. Urunov": "乌鲁诺夫",
  "S. Nasrullaev": "纳斯鲁拉耶夫",
  "G. Ramos": "贡萨洛·拉莫斯",
  "T. Araujo": "阿劳霍",
  "M. Guehi": "古埃伊",
  "M. Pasalic": "帕萨利奇",
  "I. Fatawu": "法塔乌",
  "C. Yirenkyi": "伊伦基",
  "L. Ati Zigi": "阿蒂-齐吉",
}

// 国籍英文 → 中文。
export const NAT_ZH: Record<string, string> = {
  "Argentina": "阿根廷",
  "Jordan": "约旦",
  "Brazil": "巴西",
  "Italy": "意大利",
  "Morocco": "摩洛哥",
  "Qatar": "卡塔尔",
  "El Salvador": "萨尔瓦多",
  "Australia": "澳大利亚",
  "France": "法国",
  "Germany": "德国",
  "Netherlands": "荷兰",
  "Colombia": "哥伦比亚",
  "South Africa": "南非",
  "Ecuador": "厄瓜多尔",
  "Uruguay": "乌拉圭",
  "Spain": "西班牙",
  "England": "英格兰",
  "Japan": "日本",
  "Senegal": "塞内加尔",
  "China": "中国",
  "Sweden": "瑞典",
  "Mexico": "墨西哥",
  "Iran": "伊朗",
  "Tunisia": "突尼斯",
  "Belgium": "比利时",
  "Saudi Arabia": "沙特阿拉伯",
  "Switzerland": "瑞士",
  "Curaçao": "库拉索",
  "Curacao": "库拉索",
  "Turkey": "土耳其",
  "Türkiye": "土耳其",
  "Czech Republic": "捷克",
  "Czechia": "捷克",
  "Canada": "加拿大",
  "Bosnia & Herzegovina": "波黑",
  "Bosnia and Herzegovina": "波黑",
  "Scotland": "苏格兰",
  "USA": "美国",
  "United States": "美国",
  "Haiti": "海地",
  "South Korea": "韩国",
  "Korea Republic": "韩国",
  "Egypt": "埃及",
  "Gabon": "加蓬",
  "Mauritania": "毛里塔尼亚",
  "New Zealand": "新西兰",
  "Paraguay": "巴拉圭",
  "Cape Verde": "佛得角",
  "Cabo Verde": "佛得角",
  "Ivory Coast": "科特迪瓦",
  "Côte d'Ivoire": "科特迪瓦",
  "Algeria": "阿尔及利亚",
  "Honduras": "洪都拉斯",
  "Slovenia": "斯洛文尼亚",
  "Venezuela": "委内瑞拉",
  "Portugal": "葡萄牙",
  "Croatia": "克罗地亚",
  "Norway": "挪威",
  "Iraq": "伊拉克",
  "Ghana": "加纳",
  "Panama": "巴拿马",
  "Uzbekistan": "乌兹别克斯坦",
  "DR Congo": "刚果民主共和国",
  "Congo DR": "刚果民主共和国",
  "Austria": "奥地利",
  "New Caledonia": "新喀里多尼亚",
  "Indonesia": "印度尼西亚",
  "Costa Rica": "哥斯达黎加",
  "Nigeria": "尼日利亚",
  "Cameroon": "喀麦隆",
  "Ukraine": "乌克兰",
  "Poland": "波兰",
  "Serbia": "塞尔维亚",
  "Romania": "罗马尼亚",
  "Hungary": "匈牙利",
  "Denmark": "丹麦",
  "Wales": "威尔士",
  "Russia": "俄罗斯",
  "Greece": "希腊",
  "Slovakia": "斯洛伐克",
}
